# Welcome to the Practical Exam :)
### <span style="color:purple"> **Please read the instructions, metadata and tips carefully in the practical exam PDF available on moodle!** </span>

**Also:**

-You can add as many cells as you like to answer the questions.

-You can make use of caching or persisting your RDDs or Dataframes, this may speed up performance.

**VERY IMPORTANT:** 

**- Don't forget to comment your code. Try to explain your reasoning to solve the exercises.**

**- Add your name to the .zip file submitted.**

**- Submit a .zip file. Files with other extensions will have a penalization.**

# PART A:

##  <span style="color:blue"> **0) Warmup (1 point):** </span>

#### a) Load the pages text file (pages.txt) into your DBFS:

In [0]:
%fs ls /FileStore/tables

path name size modificationTime dbfs:/FileStore/tables/PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv 19199 1718054974000 dbfs:/FileStore/tables/PORDATA_Compensation_of_employees__Euro__xlsx.csv PORDATA_Compensation_of_employees__Euro__xlsx.csv 19589 1718054437000 dbfs:/FileStore/tables/PORDATA_Compensation_of_employees_per_capita__PPS_.csv PORDATA_Compensation_of_employees_per_capita__PPS_.csv 19981 1718054046000 dbfs:/FileStore/tables/PORDATA_GDP__Euro_.csv PORDATA_GDP__Euro_.csv 19989 1718055115000 dbfs:/FileStore/tables/PORDATA_Savings_rate_of_households.csv PORDATA_Savings_rate_of_households.csv 18483 1718051156000 dbfs:/FileStore/tables/csv_countrydata.xlsx csv_countrydata.xlsx 6207 1717975519000 dbfs:/FileStore/tables/csv_pordata.xlsx csv_pordata.xlsx 6207 1717975470000 dbfs:/FileStore/tables/insurance.csv insurance.csv 55628 1717703140000 dbfs:/FileStore/tables/movielens.txt movielens.txt 616155 1716487292000 dbfs:/FileStore/tables/onlineretail.csv onlineretail.csv 45580638 1717698189000 dbfs:/FileStore/tables/pages.txt pages.txt 64 1717696625000

Using the %fs command enables us to display the DBFS root and access the file path for the pages dataset. The specific file path is: 
 dbfs:/FileStore/tables/pages.txt

#### b) Using the Page Rank algorithm, which is the most popular page? (0.5):
##### Perform all the necessary transformations to the text file and implement the Page Rank algorithm in order to answer this question

In [0]:
#The textFile method is designed to access and retrieve text file pages that have been previously imported and saved in the DBFS. It will then convert these pages into an RDD of strings, which will be stored in the variable 'pages'.

pages=sc.textFile("dbfs:/FileStore/tables/pages.txt")
pages.collect()

Out[243]: ['A -> B',
 'A -> C',
 'A -> D',
 'B -> D',
 'B -> A',
 'C -> D',
 'D -> E',
 'E -> D']

1 - Extracting key-value pairs from the RDD of strings, thereby transforming it into an RDD of tuples.

In [0]:
#We aim to execute a conversion process on the RDD of strings to obtain an RDD consisting of tuples. In this new RDD, the initial component of each tuple corresponds to the segment preceding the ' -> ' symbol, while the subsequent component represents the content following this symbol. To achieve this objective, we will employ the string.split (' -> ').

pages = pages.map(lambda string: (string.split(' -> ')[0], string.split(' -> ')[1]))
pages.collect()

Out[244]: [('A', 'B'),
 ('A', 'C'),
 ('A', 'D'),
 ('B', 'D'),
 ('B', 'A'),
 ('C', 'D'),
 ('D', 'E'),
 ('E', 'D')]

2 - Presently, having acquired our tuples and being aware that our task involves calculating contributions according to the page's rank and its neighboring pages, we move forward by structuring the data in a systematic manner that enables us to easily retrieve information about each page's neighbors. In order to achieve this, it was necessary to generate key-value tuples, with the key representing the page and the value consisting of a comprehensive list of all its neighbors.

In [0]:
#As previously stated, it is necessary to categorize the page based on its adjacent elements, therefore, the groupByKey function is utilized.

pages = pages.distinct().groupByKey()

pages.map(lambda tup : (tup[0], list(tup[1]))).collect()

Out[245]: [('C', ['D']),
 ('A', ['B', 'D', 'C']),
 ('B', ['D', 'A']),
 ('D', ['E']),
 ('E', ['D'])]

In [0]:
# The persist() is being used as a paradigm for data optimization. Due to its ability to minimize execution time and lower data processing costs, this approach is both time and money-efficient. 

pages = pages.persist()

3 - Our method must begin by assigning a default rank value of 1 to each page. Thus, we must produce an RDD for the rankings.

In [0]:
# The page is the key and the default rank of 1.0 is the value in the tuples we are generating.

ranks = pages.map(lambda tup : (tup[0], 1.0))

ranks.collect()

Out[247]: [('C', 1.0), ('A', 1.0), ('B', 1.0), ('D', 1.0), ('E', 1.0)]

In [0]:
# The getContribs function takes a list including the neighbor and the rank as input. It returns a tuple containing the new rank for each neighbor, which is dependent on the number of neighbors provided as well as the rankings from the past.


def getContribs(neighbours, rank):
  for neighbour in neighbours:
    
    yield (neighbour, rank / len(neighbours))
    
# We chose to employ n=20 since we found that the more iterations, the better the outcomes. (The page ranking gets progressively better with each iteration.)

n = 20
for i in range(n):
  
  data = pages.join(ranks)
  
  
  contribs = data.flatMap(lambda pageInfo : getContribs(pageInfo[1][0], pageInfo[1][1]))
  
  contribs = contribs.reduceByKey(lambda a, b : a+b)
  
  ranks = contribs.mapValues(lambda num : num * 0.85 + 0.15)
  
ranks.sortByKey().collect()

Out[248]: [('A', 0.24301279063208753),
 ('B', 0.2188536243756648),
 ('C', 0.2188536243756648),
 ('D', 2.2287330375074665),
 ('E', 2.090546923109115)]

PageRank algorithm gives web pages a ranking score based on links from other pages
• Higher scores given for more links and links from other high ranking pages;

This being sad, our highest rank is D, and our lowest rank B/C.

#### C) Will ignoring C's contributions change these results? (0.5):
#### In other words, exclude C as a referencing page and repeat the algorithm. 

***Note that we do not intend to discard links that reference C, only the links where C is referencing other pages.***

We will use the Page Rank Algorithm that we previously conducted one more for this exercise. But as of right now, Page C will no longer be a contributor. We will proceed in the same manner as in the last exercise after removing page C from the key.

In [0]:
# For this exercise, we are going to create a new variable called pages1, which is a list of tuples with the pages as the key and the neighbors that the pages are referencing as the value.

pages1 = pages.map(lambda tup : (tup[0], list(tup[1])))

pages1.collect()

Out[249]: [('C', ['D']),
 ('A', ['B', 'D', 'C']),
 ('B', ['D', 'A']),
 ('D', ['E']),
 ('E', ['D'])]

We choose to take the following approach in order to filter out all of the RDD tuples where the key was "C":

In [0]:
# We are filtering all the tuples with the key C using the filter() function.

pages1 = pages1.filter(lambda lt : lt[0] != 'C')

pages1.collect()

Out[250]: [('A', ['B', 'D', 'C']), ('B', ['D', 'A']), ('D', ['E']), ('E', ['D'])]

In [0]:
# The persist() function is being used as a paradigm for data optimization. It is a time- and money-efficient model since it lowers the cost of data processing and saves some execution time. 

pages1 = pages1.persist()

In [0]:
# A list of tuples with the page as the key and the default rank of 1.0 as the value is required for the algorithm.

ranks1 = pages1.map(lambda tup : (tup[0], 1.0))

ranks1.collect()

Out[252]: [('A', 1.0), ('B', 1.0), ('D', 1.0), ('E', 1.0)]

In [0]:
#The getContribs function takes a list including the neighbor and the rank as input. It then returns a tuple containing the new rank for each neighbor, which depends on the number of neighbors provided as well as the rankings from the past.

def getContribs(neighbours, rank):
  for neighbour in neighbours:
    
    yield (neighbour, rank / len(neighbours))

    
# We chose to employ n=20 since we found that the more iterations, the better the outcomes. (The page ranking gets progressively better with each iteration.)
    
n = 20
for i in range(n):
  
  data = pages1.join(ranks1)
  
  
  contribs = data.flatMap(lambda pageInfo : getContribs(pageInfo[1][0], pageInfo[1][1]))
  
  contribs = contribs.reduceByKey(lambda a, b : a+b)
  
  ranks1 = contribs.mapValues(lambda num : num * 0.85 + 0.15)
  
ranks1.sortByKey().collect()

Out[253]: [('A', 0.24301279063208753),
 ('B', 0.2188536243756648),
 ('C', 0.2188536243756648),
 ('D', 1.5726173327535289),
 ('E', 1.5064920933666854)]

After running the Page Rank Algorithm both with and without Cs as contributors, we can see that eliminating C, particularly for pages (D,E), changes the rankings' values.

##  <span style="color:blue"> **1) Data Load, Cleaning, and Feature Engineering (4 points):** </span>

#### a) Load the Online Retail file (onlineretail.csv) data into your DBFS:

In [0]:
%fs ls /FileStore/tables

path name size modificationTime dbfs:/FileStore/tables/PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv 19199 1718054974000 dbfs:/FileStore/tables/PORDATA_Compensation_of_employees__Euro__xlsx.csv PORDATA_Compensation_of_employees__Euro__xlsx.csv 19589 1718054437000 dbfs:/FileStore/tables/PORDATA_Compensation_of_employees_per_capita__PPS_.csv PORDATA_Compensation_of_employees_per_capita__PPS_.csv 19981 1718054046000 dbfs:/FileStore/tables/PORDATA_GDP__Euro_.csv PORDATA_GDP__Euro_.csv 19989 1718055115000 dbfs:/FileStore/tables/PORDATA_Savings_rate_of_households.csv PORDATA_Savings_rate_of_households.csv 18483 1718051156000 dbfs:/FileStore/tables/csv_countrydata.xlsx csv_countrydata.xlsx 6207 1717975519000 dbfs:/FileStore/tables/csv_pordata.xlsx csv_pordata.xlsx 6207 1717975470000 dbfs:/FileStore/tables/insurance.csv insurance.csv 55628 1717703140000 dbfs:/FileStore/tables/movielens.txt movielens.txt 616155 1716487292000 dbfs:/FileStore/tables/onlineretail.csv onlineretail.csv 45580638 1717698189000 dbfs:/FileStore/tables/pages.txt pages.txt 64 1717696625000

We may list the DBFS root and obtain the filepath for the Online Retail file by using the %fs command. The path to the file is: dbfs:/FileStore/tables/onlineretail.csv

#### b) Prepare the data for analysis (0.5):

##### For instance, load the data to a spark DataFrame, or create the necessary table in SparkSQL.

In [0]:
# Initially, the CSV file was imported, and the path was copied. Next, we load the data from the secretly imported CVS file using spark.read.csv.
# We set inferSchema=true since Spark will automatically retrieve the schema for each column. 
# We set the header to true because the first row of the CVS already had the column names.

data = spark.read.csv("dbfs:/FileStore/tables/onlineretail.csv", header="true", sep=",", inferSchema="true")

In [0]:
# Using the display function to see a summary of the loaded data. 

data.head(10)

Out[255]: [Row(InvoiceNo='536365', StockCode='85123A', Description='WHITE HANGING HEART T-LIGHT HOLDER', Quantity=6, InvoiceDate='12/1/2010 8:26', UnitPrice=2.55, CustomerID=17850, Country='United Kingdom'),
 Row(InvoiceNo='536365', StockCode='71053', Description='WHITE METAL LANTERN', Quantity=6, InvoiceDate='12/1/2010 8:26', UnitPrice=3.39, CustomerID=17850, Country='United Kingdom'),
 Row(InvoiceNo='536365', StockCode='84406B', Description='CREAM CUPID HEARTS COAT HANGER', Quantity=8, InvoiceDate='12/1/2010 8:26', UnitPrice=2.75, CustomerID=17850, Country='United Kingdom'),
 Row(InvoiceNo='536365', StockCode='84029G', Description='KNITTED UNION FLAG HOT WATER BOTTLE', Quantity=6, InvoiceDate='12/1/2010 8:26', UnitPrice=3.39, CustomerID=17850, Country='United Kingdom'),
 Row(InvoiceNo='536365', StockCode='84029E', Description='RED WOOLLY HOTTIE WHITE HEART.', Quantity=6, InvoiceDate='12/1/2010 8:26', UnitPrice=3.39, CustomerID=17850, Country='United Kingdom'),
 Row(InvoiceNo='536365'

In [0]:
# The chache function will also print the columns and their corresponding data types, even though it is an alias of the persist function.
data.cache()

Out[256]: DataFrame[InvoiceNo: string, StockCode: string, Description: string, Quantity: int, InvoiceDate: string, UnitPrice: double, CustomerID: int, Country: string]

In [0]:
#1. To change the data type of the InvoiceNo and the invoiceDate to int and timestamp we have to first import it the col and to_timestamp function.
#2. We are changing the type of the InvoiceDate column into the 'MM/dd/yyyy HH:mm' format.
#3. After the transformation we are just confirming if the type was successfully changed.

from pyspark.sql.functions import to_timestamp
from pyspark.sql.functions import col

spark.sql("set spark.sql.legacy.timeParserPolicy=LEGACY")

#data = data.withColumn('InvoiceNo', col('InvoiceNo').cast('int'))

data = data.withColumn('InvoiceDate',to_timestamp(data.InvoiceDate,'MM/dd/yyyy HH:mm'))

data.cache()

#We comment the transformation of InvoiceNo because we realized that we had letters.

Out[257]: DataFrame[InvoiceNo: string, StockCode: string, Description: string, Quantity: int, InvoiceDate: timestamp, UnitPrice: double, CustomerID: int, Country: string]


After checking the schema we notice that the InvoiceNo & the InvoiceDate column's data types are a string so we proceded by changing it to int, and timestamp, respectfully.

In [0]:
#We think the only variable we should look for some inconsistencys is Country, so we print the total rows of data set and then, per each Country.
from pyspark.sql import functions as F

# Total number of rows in the dataset
total_rows = data.count()
print("Total rows in the dataset:", total_rows)

# Count of rows for each country
country_counts = data.groupBy('Country').count().orderBy('Country')
country_counts.show(country_counts.count(), truncate=False)

Total rows in the dataset: 541909
+--------------------+------+
|Country             |count |
+--------------------+------+
|Australia           |1259  |
|Austria             |401   |
|Bahrain             |19    |
|Belgium             |2069  |
|Brazil              |32    |
|Canada              |151   |
|Channel Islands     |758   |
|Cyprus              |622   |
|Czech Republic      |30    |
|Denmark             |389   |
|EIRE                |8196  |
|European Community  |61    |
|Finland             |695   |
|France              |8557  |
|Germany             |9495  |
|Greece              |146   |
|Hong Kong           |288   |
|Iceland             |182   |
|Israel              |297   |
|Italy               |803   |
|Japan               |358   |
|Lebanon             |45    |
|Lithuania           |35    |
|Malta               |127   |
|Netherlands         |2371  |
|Norway              |1086  |
|Poland              |341   |
|Portugal            |1519  |
|RSA                 |58    |
|Saudi

In [0]:
#  By analysing this, we came to the conclusion that we want to replace the "European Community" with "Unspecified", as the European Community are not a Country.
from pyspark.sql.functions import regexp_replace
data = data.withColumn('Country', regexp_replace('Country', 'European Community', 'Unspecified'))

country_counts = data.groupBy('Country').count().orderBy('Country')
country_counts.show(country_counts.count(), truncate=False)


+--------------------+------+
|Country             |count |
+--------------------+------+
|Australia           |1259  |
|Austria             |401   |
|Bahrain             |19    |
|Belgium             |2069  |
|Brazil              |32    |
|Canada              |151   |
|Channel Islands     |758   |
|Cyprus              |622   |
|Czech Republic      |30    |
|Denmark             |389   |
|EIRE                |8196  |
|Finland             |695   |
|France              |8557  |
|Germany             |9495  |
|Greece              |146   |
|Hong Kong           |288   |
|Iceland             |182   |
|Israel              |297   |
|Italy               |803   |
|Japan               |358   |
|Lebanon             |45    |
|Lithuania           |35    |
|Malta               |127   |
|Netherlands         |2371  |
|Norway              |1086  |
|Poland              |341   |
|Portugal            |1519  |
|RSA                 |58    |
|Saudi Arabia        |10    |
|Singapore           |229   |
|Spain    

#### c) There are missing values in the columns CustomerID and Description. Discard all records that have null values in such columns (0.5):


We will now look for any missing data. For that we needed SQL functions isnull, when, count, col

In [0]:
# As previously indicated, we are importing a few methods that are required to examine the total amount of missing data for every column.

from pyspark.sql.functions import isnull, when, count, col
null_miss = data.select([count(when(isnull(c), c)).alias(c) for c in data.columns]).show()

+---------+---------+-----------+--------+-----------+---------+----------+-------+
|InvoiceNo|StockCode|Description|Quantity|InvoiceDate|UnitPrice|CustomerID|Country|
+---------+---------+-----------+--------+-----------+---------+----------+-------+
|        0|        0|       1454|       0|          0|        0|    135080|      0|
+---------+---------+-----------+--------+-----------+---------+----------+-------+



It is evident that there are 1454 missing values in the CustomerID and 135080 in the Description.

In [0]:
data1 = data.dropna(how="any", subset= ["CustomerID","Description"])
null_miss = data1.select([count(when(isnull(c), c)).alias(c) for c in data1.columns]).show()

+---------+---------+-----------+--------+-----------+---------+----------+-------+
|InvoiceNo|StockCode|Description|Quantity|InvoiceDate|UnitPrice|CustomerID|Country|
+---------+---------+-----------+--------+-----------+---------+----------+-------+
|        0|        0|          0|       0|          0|        0|         0|      0|
+---------+---------+-----------+--------+-----------+---------+----------+-------+



We removed the Null Values from the CustomerID and Description columns using dropna.

In [0]:
# We choose to establish the Missing_Count variable in order to clearly see how many rows were dropped. It simply calculates the difference between the number of rows in the original dataset and the number of rows in the data set where the missing values were dropped.

Missing_Count = data.count() - data1.count()
print("Number of rowns in the uncleaned data set: ", data.count())
print("Total of rows discarded:", Missing_Count)

Number of rowns in the uncleaned data set:  541909
Total of rows discarded: 135080


541909 rows make up the uncleaned data collection.

135080 rows were eliminated in total.

#### d) Discard all the records in which Quantity has a negative number (1):

In [0]:
# Even though the filter function was an option, we chose to use the where function instead. We made a replica of the private dataset, and we are only taking into account the rows where the quantity is greater than or equal to zero by using the where function. However, we thought it would be interesting to find out how many rows were removed, so we made a second duplicate of the data set and only took into account the rows with negative quantities. 

data_positive = data1.where("Quantity >= 0")
data_negative = data1.where("Quantity < 0").count()
print("There were found and discarded:", data_negative , "rows!")

There were found and discarded: 8905 rows!


#### e) Create a new feature/column that corresponds to the amount spent (amount_spent) per record (1):
##### This can be done by computing amount_spent = quantity*unit_price.

We chose to utilize the withColumn function because we needed to add a new column to our Dataframe, as demonstrated below:

In [0]:
# Since amount_spent is a monetary variable, we choose to import the round function in order to round the newly inserted column to have two decimal values.

from pyspark.sql.functions import round
data_amount = data_positive.withColumn("amount_spent", round((data_positive["Quantity"] * data_positive["UnitPrice"]),2))
data_amount.head(10)

Out[264]: [Row(InvoiceNo='536365', StockCode='85123A', Description='WHITE HANGING HEART T-LIGHT HOLDER', Quantity=6, InvoiceDate=datetime.datetime(2010, 12, 1, 8, 26), UnitPrice=2.55, CustomerID=17850, Country='United Kingdom', amount_spent=15.3),
 Row(InvoiceNo='536365', StockCode='71053', Description='WHITE METAL LANTERN', Quantity=6, InvoiceDate=datetime.datetime(2010, 12, 1, 8, 26), UnitPrice=3.39, CustomerID=17850, Country='United Kingdom', amount_spent=20.34),
 Row(InvoiceNo='536365', StockCode='84406B', Description='CREAM CUPID HEARTS COAT HANGER', Quantity=8, InvoiceDate=datetime.datetime(2010, 12, 1, 8, 26), UnitPrice=2.75, CustomerID=17850, Country='United Kingdom', amount_spent=22.0),
 Row(InvoiceNo='536365', StockCode='84029G', Description='KNITTED UNION FLAG HOT WATER BOTTLE', Quantity=6, InvoiceDate=datetime.datetime(2010, 12, 1, 8, 26), UnitPrice=3.39, CustomerID=17850, Country='United Kingdom', amount_spent=20.34),
 Row(InvoiceNo='536365', StockCode='84029E', Descriptio

#### f) Parse the invoice_date column and create one column for each of the following bits of information: year; month; day; hour. Then filter out all the invoices from 2011 (1):

Initially, we created the requested additional columns and set the column name to a more standardized name using alias. Following that, we limited the data to only include 2010 by filtering by year. Since the newly introduced columns now include the same date-related information, we ultimately made the decision to remove the InvoiceDate field. To provide you a summary of the changes we made, we also put the dataframe on display.

In [0]:
# To parse the invoiceDate, we imported the year, month, dayofmonth, and hour function.

from pyspark.sql.functions import year, month, dayofmonth, hour

data_date = data_amount.select('*', year(data_amount["InvoiceDate"]).alias('Year'), month(data_amount["InvoiceDate"]).alias('Month'), dayofmonth(data_amount["InvoiceDate"]).alias('Day'), hour(data_amount["InvoiceDate"]).alias('Hour'))

data_parse= data_date.filter("Year != 2011")
data_parse = data_parse.drop("InvoiceDate")

data_parse.head(10)

Out[265]: [Row(InvoiceNo='536365', StockCode='85123A', Description='WHITE HANGING HEART T-LIGHT HOLDER', Quantity=6, UnitPrice=2.55, CustomerID=17850, Country='United Kingdom', amount_spent=15.3, Year=2010, Month=12, Day=1, Hour=8),
 Row(InvoiceNo='536365', StockCode='71053', Description='WHITE METAL LANTERN', Quantity=6, UnitPrice=3.39, CustomerID=17850, Country='United Kingdom', amount_spent=20.34, Year=2010, Month=12, Day=1, Hour=8),
 Row(InvoiceNo='536365', StockCode='84406B', Description='CREAM CUPID HEARTS COAT HANGER', Quantity=8, UnitPrice=2.75, CustomerID=17850, Country='United Kingdom', amount_spent=22.0, Year=2010, Month=12, Day=1, Hour=8),
 Row(InvoiceNo='536365', StockCode='84029G', Description='KNITTED UNION FLAG HOT WATER BOTTLE', Quantity=6, UnitPrice=3.39, CustomerID=17850, Country='United Kingdom', amount_spent=20.34, Year=2010, Month=12, Day=1, Hour=8),
 Row(InvoiceNo='536365', StockCode='84029E', Description='RED WOOLLY HOTTIE WHITE HEART.', Quantity=6, UnitPrice=3.

In [0]:
#As we droped some rows, we will print the rows we still have on our dataset.

print("Removed", data_date.count() - data_parse.count(), "rows!")
print("We were left with", data_parse.count(),"remaining rows!")

Removed 371764 rows!
We were left with 26160 remaining rows!


## <span style="color:blue"> **2) Data Exploration (10 points):** </span>
### Using the ***data that you cleaned*** in the previous exercises, answer the following questions:

#### a) What are the top 5 customers with the highest number of orders? (1)
##### Remember that the same invoice number means one order even if it appears in many rows!

*Tip: if you opt for a query you might need to include the count of the number of distinct InvoiceNo!*

Imported SQL Context and import PySpark SQL functions

In [0]:
from pyspark.sql import SQLContext
import pyspark.sql.functions as fct

In [0]:
data_parse.groupBy('CustomerID').agg(fct.countDistinct('InvoiceNo').alias('Amount_of_Orders')).sort('Amount_of_Orders', ascending = False).limit(5).toPandas()

CustomerID 
 Amount_of_Orders 
 
 
 
 
 0 
 12748 
 35 
 
 
 1 
 17850 
 34 
 
 
 2 
 14911 
 13 
 
 
 3 
 15061 
 12 
 
 
 4 
 13777 
 10

As previously indicated, the first step involved grouping our customers based on their CustomerID. Next, we needed to count the number of invoices, keeping in mind that one invoice number corresponds to one order. We dubbed the column Amount_of_Orders appropriately, and then we sorted by this, setting the ascending to False and limit to 5, in order to display the requested information.

From the table above we can see that our top 5 Customers were the one with the respective ID: 12748, 17850, 14911, 15061 and 13777.

#### b) What are the top 5 customers with the highest money spent? (1)
##### Consider using the amount_spent column you created since it is an auxiliary column that multiplies the UnitPrice by the Quantity!

Here, we also sorted our customers by Total Amount Spent, restricting the view to 5 to identify our top 5 customers, and grouped them by CustomerID. We then added up our customers' amount_spent.

In [0]:
data_top_5 = data_parse.groupBy("CustomerID").sum("amount_spent").sort("sum(amount_spent)", ascending = False).limit(5)

# We choose to rename the column to Total_Amount_Spent in order to facilitate interpretation.
data_top_5.withColumnRenamed("sum(amount_spent)","Total_Amount_Spent").toPandas()

CustomerID 
 Total_Amount_Spent 
 
 
 
 
 0 
 18102 
 27834.61 
 
 
 1 
 15061 
 19950.66 
 
 
 2 
 16029 
 13112.52 
 
 
 3 
 14646 
 8591.88 
 
 
 4 
 14911 
 7737.94

The five most expensive clients, in order of total expenditure, were: 18021, 15061, 16029, 14646, and 14911.

#### c) What are the top 20 countries with the most orders? (1)
##### Same logic as in exercise 1, but instead of considering the customers we are considering the country.

Using the same methodology as in exercise 1, we are examining our top 20 countries based on the total number of orders. 
We didn't set a restriction of 20 because, after a few attempts, we kept getting countries with amount_of_Order = 1. Considering that we wanted to include the top 20 nations according to that variable, we added the countries where the amount of order was 1. Since we have 6 countrys with 1 order, we consider that we should show the top 21.

In [0]:
data_parse.groupBy('Country').agg(fct.countDistinct('InvoiceNo').alias('Amount_of_Orders')).sort('Amount_of_Orders', ascending = False).toPandas()

Country 
 Amount_of_Orders 
 
 
 
 
 0 
 United Kingdom 
 1291 
 
 
 1 
 Germany 
 30 
 
 
 2 
 France 
 21 
 
 
 3 
 EIRE 
 15 
 
 
 4 
 Portugal 
 6 
 
 
 5 
 Belgium 
 5 
 
 
 6 
 Lithuania 
 4 
 
 
 7 
 Spain 
 4 
 
 
 8 
 Japan 
 3 
 
 
 9 
 Australia 
 3 
 
 
 10 
 Netherlands 
 3 
 
 
 11 
 Sweden 
 2 
 
 
 12 
 Italy 
 2 
 
 
 13 
 Norway 
 2 
 
 
 14 
 Switzerland 
 2 
 
 
 15 
 Finland 
 1 
 
 
 16 
 Denmark 
 1 
 
 
 17 
 Iceland 
 1 
 
 
 18 
 Channel Islands 
 1 
 
 
 19 
 Cyprus 
 1 
 
 
 20 
 Poland 
 1 
 
 
 21 
 Austria 
 1

#### d) What are the top 5 products that are purchased the most amount of times? (1)
##### Note that by most amount of times, we do NOT consider the quantity of the order, only the fact that that item was purchased.

In [0]:
# We began by classifying the products according to their descriptions in order to clearly see which ones were the most popular purchases. Following that, the InvoiceNo was uniquely counted, and we renamed that count column using the alias. Additionally, we restricted the display to 5 products and sorted that column in descending order.

data_parse.groupBy("Description").agg(fct.countDistinct("InvoiceNo").alias("Total_Purchases")).sort("Total_Purchases", ascending = False).limit(5).toPandas()

Description 
 Total_Purchases 
 
 
 
 
 0 
 WHITE HANGING HEART T-LIGHT HOLDER 
 201 
 
 
 1 
 REGENCY CAKESTAND 3 TIER 
 138 
 
 
 2 
 HAND WARMER BABUSHKA DESIGN 
 137 
 
 
 3 
 PAPER CHAIN KIT 50'S CHRISTMAS 
 132 
 
 
 4 
 SCOTTIE DOG HOT WATER BOTTLE 
 130

The table above shows the top 5 products that were purchased the most amount of times.

#### e)  What is the name (Description) of the most expensive item? (3)

In [0]:
# In order to execute various transformations ahead, we are importing some PySpark SQL functions, such as the max and the avg.
from pyspark.sql.functions import max, avg

In [0]:
# The products are grouped based on their description. The UnitPrice was then uniquely tallied, and the column was sorted in descending order to display only 10 products. We took that action to check if the product prices changed over time.

data_parse.groupBy("Description").agg(fct.countDistinct("UnitPrice")).sort("count(UnitPrice)", ascending = False).limit(10).toPandas()

Description 
 count(UnitPrice) 
 
 
 
 
 0 
 Manual 
 18 
 
 
 1 
 POSTAGE 
 5 
 
 
 2 
 PLEASE ONE PERSON METAL SIGN 
 4 
 
 
 3 
 PACK OF 72 SKULL CAKE CASES 
 3 
 
 
 4 
 HEART OF WICKER LARGE 
 3 
 
 
 5 
 WOODEN OWLS LIGHT GARLAND 
 3 
 
 
 6 
 VANILLA INCENSE IN TIN 
 3 
 
 
 7 
 RED TOADSTOOL LED NIGHT LIGHT 
 3 
 
 
 8 
 REGENCY CAKESTAND 3 TIER 
 3 
 
 
 9 
 PACK OF 60 PINK PAISLEY CAKE CASES 
 3

After confirming our assumptions by first examining our items to see if the unit costs had changed over time, we decided to offer the remedy in two alternative ways:

1 - By grouping our products by the avg Unit Price

2 - By grouping our products by the max Unit Price

In [0]:
#In this first method, we'll add up the products in the group based on their average price and round the results to two decimal places.We renamed the column using an alias and sorted it by decreasing order using the same reasoning as before. Lastly, we restricted the view so that it only displayed the best item.

data_parse.groupBy("Description").agg(fct.round(avg("UnitPrice"),2).alias("AVG_Unit_Price")).sort("AVG_Unit_Price", ascending = False).limit(1).toPandas()

Description 
 AVG_Unit_Price 
 
 
 
 
 0 
 LOVE SEAT ANTIQUE WHITE METAL 
 175.0


With a price per unit of 175, Love Seat Antique White Metal was, on average, the most expensive product when taking into account the output above.

In [0]:
# The second strategy uses the maximum product price together with the same logic as the previous one.

data_parse.groupBy("Description").agg(fct.round(max("UnitPrice"),2).alias("MAX_Unit_Price")).sort("MAX_Unit_Price", ascending = False).limit(1).toPandas()

Description 
 MAX_Unit_Price 
 
 
 
 
 0 
 VINTAGE RED KITCHEN CABINET 
 295.0

With a price per unit of 295, the Vintage Red Kitchen Cabinet was the most costly product when looking at the output above.

#### f) What are the top ten most popular words in the Description column? (3)

##### This is a word count exercise.
*Tip: you can use `.rdd` to convert a dataframe to an RDD. This will be an RDD of row objects. Make sure your top 5 words are actually words, you may have to remove empty strings!*

In [0]:
# We are making a duplicate of the cleaned (parse) dataset specifically for this exercise, but we are excluding the description column.
# We are then developing an RDD after that. This string collection has each string representing a phrase.
# We are showing the first 10 lines.

data_description=data_parse.select("Description")

dataRDD=data_description.rdd.flatMap(list)
dataRDD.take(10)

Out[276]: ['WHITE HANGING HEART T-LIGHT HOLDER',
 'WHITE METAL LANTERN',
 'CREAM CUPID HEARTS COAT HANGER',
 'KNITTED UNION FLAG HOT WATER BOTTLE',
 'RED WOOLLY HOTTIE WHITE HEART.',
 'SET 7 BABUSHKA NESTING BOXES',
 'GLASS STAR FROSTED T-LIGHT HOLDER',
 'HAND WARMER UNION JACK',
 'HAND WARMER RED POLKA DOT',
 'ASSORTED COLOUR BIRD ORNAMENT']

First, we divided each line into its component words so that each word could be added to a list of strings.

In [0]:
data_split = dataRDD.flatMap(lambda line: line.split(" "))

data_split.collect

Out[277]: <bound method RDD.collect of PythonRDD[3964] at RDD at PythonRDD.scala:58>

Since the same word can be expressed in multiple ways (White, WHITE), we are lowering the data such that it becomes a normalized list of strings.

In [0]:
data_lowered = data_split.map(lambda x: str(x).lower())

data_lowered.collect

Out[278]: <bound method RDD.collect of PythonRDD[3965] at RDD at PythonRDD.scala:58>

As we read through the description, we discovered that several words—like "LIGHT," "LIGHTS,"—appeared written with different punctuation. As a result, we had to figure out how to remove it.

In [0]:
import string
data_punctuation = data_lowered.map(lambda word: word.translate(str.maketrans('', '', string.punctuation)))

data_punctuation.collect

Out[279]: <bound method RDD.collect of PythonRDD[3966] at RDD at PythonRDD.scala:58>

There were some problems we had with strings like this, '', in our list. Consequently, we needed to figure out how to limit the strings in our list such that len(string)>0.

In [0]:
data_clean = data_punctuation.filter(lambda x: len(x) > 0)

Each word in the word count had to be given a 1 so that we could add up all the 1s for each word and find the total number of times each word occurred. With that, we produced tuples with the word as the key and 1 as the value. We then reducedByKey to get the sum.

In [0]:
word_count = data_clean.map(lambda word: (word, 1)).reduceByKey(lambda x, y: x + y)

word_count.collect()

Out[281]: [('heart', 2067),
 ('metal', 983),
 ('water', 1216),
 ('set', 1996),
 ('nesting', 64),
 ('warmer', 651),
 ('polka', 26),
 ('bird', 363),
 ('poppys', 179),
 ('charlotte', 197),
 ('mug', 614),
 ('of', 1924),
 ('blocks', 51),
 ('alphabet', 50),
 ('paris', 44),
 ('panda', 7),
 ('gift', 210),
 ('inflatable', 16),
 ('card', 470),
 ('of4', 38),
 ('i', 277),
 ('toadstool', 95),
 ('led', 56),
 ('christmas', 1600),
 ('finish', 249),
 ('frame', 359),
 ('plates', 24),
 ('cases', 485),
 ('charlielola', 36),
 ('gin', 73),
 ('cup', 236),
 ('flowers', 67),
 ('money', 135),
 ('cloche', 16),
 ('tidy', 54),
 ('baskets', 23),
 ('board', 89),
 ('chalkboard', 89),
 ('flower', 182),
 ('bread', 64),
 ('ribbons', 244),
 ('decoration', 491),
 ('10', 179),
 ('flying', 31),
 ('rain', 38),
 ('hat', 14),
 ('deluxe', 39),
 ('soldier', 27),
 ('24', 93),
 ('orange', 73),
 ('12', 492),
 ('purse', 138),
 ('poorly', 76),
 ('4', 298),
 ('family', 36),
 ('silver', 380),
 ('mirror', 70),
 ('served', 11),
 ('im', 1

In [0]:
word_count.sortBy(lambda key: key[1],ascending=False).take(10)

Out[282]: [('red', 2318),
 ('heart', 2067),
 ('set', 1996),
 ('of', 1924),
 ('retrospot', 1909),
 ('christmas', 1600),
 ('bag', 1533),
 ('box', 1432),
 ('white', 1343),
 ('design', 1337)]

These are the 10 words that most appear in our csv description and we sorted them by descending order.

# PART B:

## <span style="color:blue"> **Machine Learning (3 points):** </span>

#### a) Load the insurance dataset and perform the following operations: (0.5)
##### - Filter out (remove from the dataset) the region column.
##### - Encode the values in the smoker column in the following manner:
1. If the person is a smoker his/her value in this column should be 1
2. If the person is not a smoker his/her value in this column should be 0

In [0]:
%fs ls /FileStore/tables

path name size modificationTime dbfs:/FileStore/tables/PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv 19199 1718054974000 dbfs:/FileStore/tables/PORDATA_Compensation_of_employees__Euro__xlsx.csv PORDATA_Compensation_of_employees__Euro__xlsx.csv 19589 1718054437000 dbfs:/FileStore/tables/PORDATA_Compensation_of_employees_per_capita__PPS_.csv PORDATA_Compensation_of_employees_per_capita__PPS_.csv 19981 1718054046000 dbfs:/FileStore/tables/PORDATA_GDP__Euro_.csv PORDATA_GDP__Euro_.csv 19989 1718055115000 dbfs:/FileStore/tables/PORDATA_Savings_rate_of_households.csv PORDATA_Savings_rate_of_households.csv 18483 1718051156000 dbfs:/FileStore/tables/csv_countrydata.xlsx csv_countrydata.xlsx 6207 1717975519000 dbfs:/FileStore/tables/csv_pordata.xlsx csv_pordata.xlsx 6207 1717975470000 dbfs:/FileStore/tables/insurance.csv insurance.csv 55628 1717703140000 dbfs:/FileStore/tables/movielens.txt movielens.txt 616155 1716487292000 dbfs:/FileStore/tables/onlineretail.csv onlineretail.csv 45580638 1717698189000 dbfs:/FileStore/tables/pages.txt pages.txt 64 1717696625000

We may list the DBFS root and obtain the filepath for the insurance dataset by using the %fs command./FileStore/tables/insurance.csv is the filepath.

In [0]:
# Initially, we copied the path and imported the CSV file. Next, we load the data from the secretly imported CVS file using spark.read.csv.We set inferSchema=true since Spark will automatically retrieve the schema for each column. We set the header to true because the first row of the CVS already had the column names.

insurance = spark.read.csv("/FileStore/tables/insurance.csv", header="true", sep=",", inferSchema="true")

In [0]:
# As previously stated, the persist() function that we previously used is an alias for the cache() function. This was done so that we could comprehend each column's data type better.
insurance.cache()

Out[284]: DataFrame[age: int, sex: string, bmi: double, children: int, smoker: string, region: string, charges: double]

In [0]:
#Showing the dataset so that we can see an overview of our analysis.

insurance.head(10)

Out[285]: [Row(age=19, sex='female', bmi=27.9, children=0, smoker='yes', region='southwest', charges=16884.924),
 Row(age=18, sex='male', bmi=33.77, children=1, smoker='no', region='southeast', charges=1725.5523),
 Row(age=28, sex='male', bmi=33.0, children=3, smoker='no', region='southeast', charges=4449.462),
 Row(age=33, sex='male', bmi=22.705, children=0, smoker='no', region='northwest', charges=21984.47061),
 Row(age=32, sex='male', bmi=28.88, children=0, smoker='no', region='northwest', charges=3866.8552),
 Row(age=31, sex='female', bmi=25.74, children=0, smoker='no', region='southeast', charges=3756.6216),
 Row(age=46, sex='female', bmi=33.44, children=1, smoker='no', region='southeast', charges=8240.5896),
 Row(age=37, sex='female', bmi=27.74, children=3, smoker='no', region='northwest', charges=7281.5056),
 Row(age=37, sex='male', bmi=29.83, children=2, smoker='no', region='northeast', charges=6406.4107),
 Row(age=60, sex='female', bmi=25.84, children=0, smoker='no', region='n

In [0]:
# importing rge StringIndexer so we can create the desired column encoded.
from pyspark.ml.feature import StringIndexer

SmokerIndexer = StringIndexer(inputCol ="smoker", outputCol ="Smoker_Index")

insurance_1 = SmokerIndexer.fit(insurance).transform(insurance)

insurance_1.head(10)

Out[286]: [Row(age=19, sex='female', bmi=27.9, children=0, smoker='yes', region='southwest', charges=16884.924, Smoker_Index=1.0),
 Row(age=18, sex='male', bmi=33.77, children=1, smoker='no', region='southeast', charges=1725.5523, Smoker_Index=0.0),
 Row(age=28, sex='male', bmi=33.0, children=3, smoker='no', region='southeast', charges=4449.462, Smoker_Index=0.0),
 Row(age=33, sex='male', bmi=22.705, children=0, smoker='no', region='northwest', charges=21984.47061, Smoker_Index=0.0),
 Row(age=32, sex='male', bmi=28.88, children=0, smoker='no', region='northwest', charges=3866.8552, Smoker_Index=0.0),
 Row(age=31, sex='female', bmi=25.74, children=0, smoker='no', region='southeast', charges=3756.6216, Smoker_Index=0.0),
 Row(age=46, sex='female', bmi=33.44, children=1, smoker='no', region='southeast', charges=8240.5896, Smoker_Index=0.0),
 Row(age=37, sex='female', bmi=27.74, children=3, smoker='no', region='northwest', charges=7281.5056, Smoker_Index=0.0),
 Row(age=37, sex='male', bmi=

#### b) Perform a multiple linear regression in an attempt to predict the health insurance charges based on the clients information. At the end report the coeficients, the RMSE and the r2 of the model: (2.5)

##### Make sure to consider any transformation necessary to the dataframe (e.g., deriving new variables, dropping existing ones, scale transformations , etc...) Justify all your decisions.

In [0]:
#Import of libraries necessaries
from pyspark.ml.regression import LinearRegression
from pyspark.ml.feature import VectorAssembler
from pyspark.ml import Pipeline

We carried out some exploratory research in order to gain a deeper understanding of the data in our dataset. Using the dataset from the prior exercise, we carried on.

In [0]:
# We made the decision to reexamine the data types in order to obtain a deeper understanding of the data on which we will be performing the regression.
insurance_1.printSchema()

root
 |-- age: integer (nullable = true)
 |-- sex: string (nullable = true)
 |-- bmi: double (nullable = true)
 |-- children: integer (nullable = true)
 |-- smoker: string (nullable = true)
 |-- region: string (nullable = true)
 |-- charges: double (nullable = true)
 |-- Smoker_Index: double (nullable = false)



In [0]:
display(insurance_1.describe())

summary age sex bmi children smoker region charges Smoker_Index count 1338 1338 1338 1338 1338 1338 1338 1338 mean 39.20702541106129 null 30.663396860986538 1.0949177877429 null null 13270.422265141257 0.20478325859491778 stddev 14.049960379216147 null 6.098186911679012 1.205492739781914 null null 12110.011236693992 0.40369403754561717 min 18 female 15.96 0 no northeast 1121.8739 0.0 max 64 male 53.13 5 yes southwest 63770.42801 1.0

As all of our columns have the same count as the number of rows, our summary statistics show that there are no missing data. Additionally, we can see that our target column, charges, has a significant discrepancy between its minimum and maximum values. Based on this, we can deduce that the column is highly skewed. Upon looking at the age column, we can see that our sample is not that elderly, with a mean age of 39 and a standard deviation of 14. The majority of our group is overweight, as indicated by the bmi mean of thirty. The children variable indicates how many children there are in this situation; the mean is 1, the max is 5, and the min is 0.

As with the Smoker, we need to pay close attention to the "sex" column because we want to create the correlation matrix. In order to perform the correlation matrix between all the variables, we must encode that variable.

In [0]:
# Using the StringIndexer to encode the sex variable like we did before.
SexIndexer = StringIndexer(inputCol ="sex", outputCol ="Sex_Index")

insurance_1 = SexIndexer.fit(insurance_1).transform(insurance_1)

insurance_1.head(10)

Out[290]: [Row(age=19, sex='female', bmi=27.9, children=0, smoker='yes', region='southwest', charges=16884.924, Smoker_Index=1.0, Sex_Index=1.0),
 Row(age=18, sex='male', bmi=33.77, children=1, smoker='no', region='southeast', charges=1725.5523, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=28, sex='male', bmi=33.0, children=3, smoker='no', region='southeast', charges=4449.462, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=33, sex='male', bmi=22.705, children=0, smoker='no', region='northwest', charges=21984.47061, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=32, sex='male', bmi=28.88, children=0, smoker='no', region='northwest', charges=3866.8552, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=31, sex='female', bmi=25.74, children=0, smoker='no', region='southeast', charges=3756.6216, Smoker_Index=0.0, Sex_Index=1.0),
 Row(age=46, sex='female', bmi=33.44, children=1, smoker='no', region='southeast', charges=8240.5896, Smoker_Index=0.0, Sex_Index=1.0),
 Row(age=37, sex='female', bmi=27.74, childre

In [0]:
#Having columns that wouldn't fit the coorelation matrix, we divide them in 2 segments. Categorical and numerical.

from pyspark.sql import SparkSession

# Assuming `insurance_1` is your PySpark DataFrame
spark = SparkSession.builder.getOrCreate()

# Create insurance_categorical DataFrame with 'region' column
insurance_categorical = insurance_1.select('region')

# Create insurance_numerical DataFrame with specified columns
insurance_numerical = insurance_1.select('age', 'bmi', 'children', 'charges', 'Smoker_Index', 'Sex_Index')

# Show the first few rows of each DataFrame
insurance_categorical.head(10)
insurance_numerical.head(10)


Out[291]: [Row(age=19, bmi=27.9, children=0, charges=16884.924, Smoker_Index=1.0, Sex_Index=1.0),
 Row(age=18, bmi=33.77, children=1, charges=1725.5523, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=28, bmi=33.0, children=3, charges=4449.462, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=33, bmi=22.705, children=0, charges=21984.47061, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=32, bmi=28.88, children=0, charges=3866.8552, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=31, bmi=25.74, children=0, charges=3756.6216, Smoker_Index=0.0, Sex_Index=1.0),
 Row(age=46, bmi=33.44, children=1, charges=8240.5896, Smoker_Index=0.0, Sex_Index=1.0),
 Row(age=37, bmi=27.74, children=3, charges=7281.5056, Smoker_Index=0.0, Sex_Index=1.0),
 Row(age=37, bmi=29.83, children=2, charges=6406.4107, Smoker_Index=0.0, Sex_Index=0.0),
 Row(age=60, bmi=25.84, children=0, charges=28923.13692, Smoker_Index=0.0, Sex_Index=1.0)]

##CORRELATION MATRIX

In [0]:
# We choose to use Pandas Seaborn to complete the correlation matrix.
from pyspark.mllib.stat import Statistics
import pandas as pd

# outcome is compatible with Seaborn's heatmap.
def compute_correlation_matrix(df, method='pearson'):
    
    df_rdd = df.rdd.map(lambda row: row[0:])
    corr_mat = Statistics.corr(df_rdd, method=method)
    corr_mat_df = pd.DataFrame(corr_mat,
                    columns=df.columns, 
                    index=df.columns)
    return corr_mat_df

In [0]:
compute_correlation_matrix(insurance_numerical, method='pearson')

age 
 bmi 
 children 
 charges 
 Smoker_Index 
 Sex_Index 
 
 
 
 
 age 
 1.000000 
 0.109272 
 0.042469 
 0.299008 
 -0.025019 
 0.020856 
 
 
 bmi 
 0.109272 
 1.000000 
 0.012759 
 0.198341 
 0.003750 
 -0.046371 
 
 
 children 
 0.042469 
 0.012759 
 1.000000 
 0.067998 
 0.007673 
 -0.017163 
 
 
 charges 
 0.299008 
 0.198341 
 0.067998 
 1.000000 
 0.787251 
 -0.057292 
 
 
 Smoker_Index 
 -0.025019 
 0.003750 
 0.007673 
 0.787251 
 1.000000 
 -0.076185 
 
 
 Sex_Index 
 0.020856 
 -0.046371 
 -0.017163 
 -0.057292 
 -0.076185 
 1.000000

We can see from our correlation matrix that there isn't much of a link between the variables. With the exception of Smoker_Index, which has a 0.787 correlation with our goal variable.

##Train/Test Split

In [0]:
# We decided to split our dataset in 70/30.

(Insurance_Train,Insurance_Test) = insurance_numerical.randomSplit([0.7,0.3])

print("We have %d training examples and %d test examples." % (Insurance_Train.count(), Insurance_Test.count()))

We have 914 training examples and 424 test examples.


##Outliers

We are taking a broad look at potential outliers that could exist for certain variables. by switching to a boxplot and presenting the relevant variable.

In [0]:
display(Insurance_Train.select('age'))

age 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 39 39 39 39 39 39 39 39 39 39 39 39 39 39 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 43 44 44 44 44 44 44 44 44 44 44 44 44 44 44 44 44 44 44 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 46 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 51 51 51 51 51 51 51 51 51 51 51 51 51 51 51 51 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 52 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 54 54 54 54 54 54 54 54 54 54 54 54 54 54 54 54 54 54 54 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 56 56 56 56 56 56 56 56 56 56 56 56 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 57 58 58 58 58 58 58 58 58 58 58 58 58 58 58 58 58 58 58 59 59 59 59 59 59 59 59 59 59 59 59 59 59 59 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 61 61 61 61 61 61 61 61 61 61 61 61 61 61 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 62 63 63 63 63 63 63 63 63 63 63 63 63 63 64 64 64 64 64 64 64 64 64 64 64 64 64

Databricks visualization. Run in Databricks to view.

In [0]:
display(Insurance_Train.select('bmi'))

bmi 15.96 20.79 21.47 21.565 21.66 21.78 22.99 23.085 23.21 23.32 23.75 24.09 25.08 25.175 26.125 26.18 26.315 26.73 27.28 28.31 29.165 29.37 30.115 30.115 30.14 30.305 30.4 31.13 31.35 31.68 31.73 32.12 33.155 33.535 33.66 33.77 34.1 34.43 35.625 36.85 36.85 37.29 37.29 38.28 38.28 38.665 39.14 39.16 39.82 40.185 40.26 40.28 41.14 43.01 53.13 17.8 18.6 19.8 20.425 20.615 21.7 22.515 22.61 23.4 24.51 24.605 24.7 25.745 27.6 27.835 28.3 28.31 28.4 28.7 28.88 28.9 29.07 29.8 30.02 30.25 30.4 30.59 30.59 30.59 31.825 31.92 32.11 32.49 33.1 33.11 34.4 34.7 34.8 35.15 35.4 35.53 37.43 39.615 40.5 22.42 26.84 27.93 28.025 28.785 28.975 29.6 29.735 30.685 31.46 31.92 33.0 33.3 33.33 35.625 37.0 40.47 17.4 20.235 21.85 21.89 23.21 25.7 25.745 25.8 26.03 26.4 27.36 31.255 32.68 34.6 34.87 35.53 36.86 39.49 19.95 23.18 27.1 28.05 28.31 28.88 30.4 30.4 31.02 31.35 32.11 33.77 35.6 36.0 37.07 37.62 39.5 52.58 17.385 23.845 24.225 26.51 27.36 28.12 28.31 28.49 31.4 31.73 32.56 32.7 32.78 33.4 34.865 34.96 37.1 39.27 41.91 42.75 20.52 22.6 23.21 23.4 23.655 25.27 26.6 26.79 27.6 27.72 28.5 28.5 29.3 30.1 33.345 33.63 33.99 39.49 40.15 20.8 23.465 24.3 24.985 25.74 25.84 26.695 26.79 29.7 30.2 30.3 30.59 32.23 33.33 33.66 35.625 41.325 42.13 45.54 17.195 17.67 19.8 20.8 22.61 27.06 27.265 28.785 29.355 29.45 29.48 29.64 29.92 30.0 31.065 32.49 34.2 35.42 42.4 46.53 17.955 18.905 20.045 23.1 23.21 24.1 25.175 26.03 29.15 30.3 30.59 31.255 32.395 32.67 33.155 33.66 34.8 42.13 23.8 23.98 25.935 26.51 26.98 28.88 29.26 31.68 33.0 33.0 33.11 33.4 33.82 34.77 38.06 20.235 21.755 22.895 25.6 25.9 26.03 27.2 27.94 28.975 29.59 32.11 33.345 34.4 35.5 35.53 37.29 38.83 38.94 19.95 22.895 22.99 24.13 24.4 25.46 27.645 28.38 28.405 30.9 31.4 32.4 35.3 35.53 37.43 37.8 38.83 39.05 43.12 44.22 20.4 25.74 25.9 25.935 27.645 28.5 28.595 29.1 29.26 31.065 31.065 32.68 32.775 34.39 36.63 38.095 38.39 39.49 17.765 24.6 27.835 28.12 28.88 28.93 29.59 29.735 29.8 31.5 31.54 33.155 33.63 37.145 37.18 37.335 41.1 44.22 19.095 22.705 24.31 24.605 26.695 27.1 27.455 28.27 32.9 33.44 35.245 35.53 35.75 35.75 38.9 39.82 42.4 42.46 42.94 21.375 22.42 23.56 25.27 25.3 26.41 26.73 29.26 30.21 30.8 32.8 33.7 34.21 34.675 35.815 42.13 42.9 26.125 27.1 27.7 27.74 28.025 28.9 30.5 31.0 34.105 34.21 34.8 35.86 36.67 38.6 39.71 19.855 22.135 22.6 25.84 25.9 26.885 27.55 28.595 29.04 29.92 33.4 33.82 34.43 35.2 41.895 17.29 22.705 23.37 24.32 26.4 27.74 28.025 29.5 29.64 29.8 29.83 30.78 30.8 30.8 30.875 34.1 34.105 34.2 34.8 37.07 46.53 47.6 19.3 19.95 19.95 21.12 27.265 27.6 27.835 28.0 28.27 30.21 30.69 31.0 34.7 34.8 37.73 38.39 21.85 23.275 24.225 24.89 26.315 29.925 32.5 32.8 34.1 34.1 35.3 41.8 42.655 45.43 22.22 22.705 24.97 25.08 25.46 26.315 27.4 28.12 28.69 29.3 29.355 29.6 29.81 30.875 32.3 32.775 33.0 34.105 41.69 21.755 21.78 23.94 28.05 28.31 28.405 28.8 29.64 30.59 30.78 31.02 32.2 32.6 33.06 34.2 34.21 35.75 36.08 37.1 40.26 23.37 24.605 24.86 24.985 26.07 26.125 26.18 26.6 29.0 30.0 31.255 32.87 33.155 34.1 35.97 36.195 37.18 37.9 40.37 20.045 20.13 24.7 25.27 26.03 26.7 26.885 27.36 27.8 30.1 30.685 32.56 32.6 34.58 34.96 35.31 35.64 35.72 35.97 21.85 22.135 23.98 25.0 25.365 25.8 27.5 27.645 29.735 29.81 31.35 34.32 36.48 37.1 38.06 38.95 39.52 43.89 20.35 21.375 22.895 22.895 24.31 25.175 25.7 27.5 27.83 28.7 30.2 30.495 30.495 30.9 33.1 33.7 36.3 38.285 39.805 39.995 19.95 22.3 23.655 24.795 25.745 25.8 27.6 27.72 27.74 28.9 30.495 32.3 33.345 33.44 33.725 34.6 35.53 39.425 40.375 43.89 48.07 19.19 23.6 24.1 24.32 25.41 26.125 27.645 28.215 28.215 29.37 29.545 29.8 29.83 32.0 32.3 33.345 36.0 36.08 36.19 36.2 36.63 38.94 47.52 22.8 25.85 27.265 27.36 28.0 28.88 28.9 29.6 29.7 30.78 31.445 32.23 32.3 32.3 33.11 33.33 35.91 40.15 41.23 21.3 22.515 22.61 23.18 23.845 25.84 27.17 28.7 29.83 29.925 30.78 31.35 32.3 33.345 34.77 36.85 37.51 41.47 42.68 23.54 25.3 25.6 26.22 26.41 27.36 27.455 27.6 27.83 28.12 30.115 30.97 31.6 31.825 32.11 32.3 32.3 33.7 34.2 36

Databricks visualization. Run in Databricks to view.

In [0]:
display(Insurance_Train.select('children'))

children 0 0 0 0 0 2 0 0 0 1 0 1 0 0 0 2 0 0 3 1 0 1 0 0 0 0 3 0 0 2 0 2 0 0 0 1 0 0 0 0 0 0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 2 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 3 5 0 1 3 1 2 0 4 2 0 0 1 0 0 2 0 0 0 0 0 3 0 0 0 1 0 0 0 3 1 0 0 0 0 2 1 0 1 1 0 2 0 1 0 0 1 0 3 0 3 2 0 0 3 3 2 0 1 0 0 0 0 0 0 0 1 0 0 0 2 0 3 0 4 0 0 0 1 0 3 2 0 1 4 2 3 0 0 0 1 2 4 0 0 1 2 2 0 1 0 0 0 3 0 2 0 1 4 1 1 0 1 2 0 1 1 2 3 3 0 1 0 0 0 0 3 1 1 1 0 2 0 1 0 2 3 1 2 2 1 2 0 2 3 0 0 0 0 0 2 1 0 4 0 0 0 0 1 1 2 2 0 2 0 2 3 1 3 1 2 1 3 0 1 1 1 3 1 1 0 0 3 2 1 3 2 2 0 0 3 1 2 5 1 0 1 0 3 1 2 3 2 1 2 1 2 0 1 4 0 1 1 0 2 1 1 3 1 3 2 1 0 0 2 0 0 2 0 1 2 1 2 5 0 0 1 2 3 1 5 1 3 0 2 0 1 2 1 1 3 1 0 1 1 0 0 0 2 1 0 1 3 2 0 3 1 1 3 1 1 2 1 1 4 0 3 2 0 1 0 3 3 4 1 2 1 2 1 3 2 3 2 2 0 3 2 2 0 0 2 0 0 2 3 4 1 1 2 1 3 2 0 1 2 3 1 0 2 3 1 3 1 1 2 2 0 3 1 3 5 3 2 1 1 0 2 3 2 0 0 2 2 2 2 0 1 1 1 1 3 4 1 0 1 4 2 1 3 1 0 1 1 1 1 1 1 1 5 2 3 0 2 3 2 2 1 1 1 2 0 0 2 0 2 1 2 1 0 1 0 0 0 1 0 2 1 2 0 2 2 2 2 1 0 2 0 3 0 1 2 3 2 1 1 2 1 2 3 3 2 2 1 1 1 1 0 2 2 1 1 0 2 0 0 0 2 3 0 0 2 5 2 3 3 2 2 1 1 2 2 0 1 2 0 0 3 2 0 1 3 3 5 0 1 0 2 3 2 1 1 1 1 0 1 2 3 2 1 1 1 0 1 1 2 3 4 1 1 3 3 1 1 0 1 1 0 1 1 2 1 0 3 1 1 1 1 0 0 0 3 1 1 1 2 0 0 1 0 4 1 0 1 2 3 2 0 1 1 0 1 1 3 2 1 0 2 4 2 2 0 0 2 0 0 1 1 3 3 1 3 2 0 2 1 2 4 2 0 0 1 1 0 0 1 4 1 0 1 3 1 2 3 2 0 0 0 2 0 0 1 2 3 0 1 0 2 3 2 0 3 0 0 2 2 2 3 5 1 0 1 1 2 1 0 3 3 0 0 0 1 0 2 0 0 1 3 3 1 3 0 2 3 3 1 1 2 1 0 0 1 0 3 1 1 2 3 1 3 0 1 0 0 0 2 2 0 0 1 2 0 2 3 0 1 0 0 0 0 0 0 0 1 0 0 0 2 1 0 0 0 0 1 2 0 4 0 0 0 0 0 0 1 0 2 2 0 0 1 1 0 0 0 0 0 0 2 1 1 0 0 0 0 2 0 0 0 0 0 0 0 0 0 3 3 0 0 3 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 2 4 0 0 0 3 1 1 0 0 0 0 0 1 0 0 2 3 1 0 0 0 1 0 2 0 0 0 0 0 0 0 0 2 0 3 1 0 0 0 0 0 0 1 2 2 0 1 0 0 3 0 0 0

Databricks visualization. Run in Databricks to view.

In [0]:
display(Insurance_Train.select('charges'))

charges 1694.7964 1607.5101 1702.4553 13747.87235 14283.4594 11884.04858 1704.5681 1704.70015 1121.8739 1711.0268 1705.6245 2201.0971 2196.4732 15518.18025 1708.92575 2304.0022 2198.18985 1615.7667 18223.4512 11272.33139 7323.734819 1719.4363 2203.47185 21344.8467 1131.5066 2203.73595 3481.868 1621.8827 1622.1885 34303.1672 33732.6867 2801.2588 2207.69745 34617.84065 1136.3994 1725.5523 1137.011 1137.4697 2211.13075 1629.8335 36149.4835 1141.4451 2219.4451 1631.8212 14133.03775 3393.35635 12890.05765 1633.0444 1633.9618 2217.46915 1634.5734 2217.6012 1146.7966 1149.3959 1163.4627 1727.785 1728.897 1241.565 1625.43375 2803.69785 13844.506 2117.33885 1628.4709 2913.569 2709.1119 2709.24395 1737.376 2710.82855 1252.407 1635.73365 17081.08 17468.9839 2331.519 1253.936 17748.5062 1743.214 17352.6803 1744.465 33307.5508 32548.3405 1256.299 1639.5631 1639.5631 24059.68019 2719.27975 33750.2918 2130.6759 36898.73308 23082.95533 34439.8559 1261.859 36397.576 34779.615 2134.9015 1263.249 1646.4297 2138.0707 2730.10785 1759.338 14711.7438 17085.2676 1967.0227 17560.37975 2457.21115 2257.47525 1875.344 1769.53165 33475.81715 1877.9294 2261.5688 1880.07 1880.487 1391.5287 37465.34375 4830.63 1984.4533 2585.269 3861.20965 15359.1045 3180.5101 1515.3449 17942.106 3279.86855 2007.945 2102.2647 2597.779 2104.1134 1909.52745 26018.95052 2020.177 2020.5523 1532.4697 1917.3184 2026.9741 4005.4225 2731.9122 2154.361 2155.6815 2639.0429 2250.8352 2741.948 33907.548 35595.5898 2643.2685 2055.3249 1674.6323 35585.576 2166.732 37484.4493 37165.1638 1682.597 44501.3982 2775.19215 2395.17155 22395.74424 1815.8759 2789.0574 2690.1138 18033.9679 18328.2381 34166.273 36189.1017 1824.2854 3591.48 36021.0112 10795.93733 2899.48935 4466.6214 3597.596 3500.6123 1837.2819 40904.1995 14571.8908 2457.502 25081.76784 1969.614 2352.96845 3044.2133 3046.062 12609.88702 18955.22017 2464.6188 35147.52848 3537.703 1977.815 4234.927 2855.43755 17128.42608 2473.3341 2480.9791 38126.2465 3208.787 3206.49135 4391.652 23241.47453 2137.6536 3309.7926 4877.98105 4189.1131 19933.458 33900.653 2632.992 2727.3951 18218.16139 36124.5737 4504.6624 2534.39375 17878.90068 3238.4357 42112.2356 14455.64405 2680.9493 3378.91 2302.3 3176.8159 17043.3414 4661.28635 3385.39915 4564.19145 2897.3235 3392.3652 24671.66334 3392.9768 2904.088 2699.56835 3490.5491 3987.926 2322.6218 3410.324 2927.0647 15006.57945 4827.90495 16420.49455 2483.736 3561.8889 2974.126 3558.62025 3070.8087 18246.4955 4260.744 16796.41194 3956.07145 18903.49141 2497.0383 4058.71245 2498.4144 3577.999 39611.7577 3847.674 17663.1442 4133.64165 4340.4409 4435.0942 4337.7352 4438.2634 34672.1472 4349.462 4449.462 3171.6149 3172.018 19673.33573 3556.9223 2689.4954 4906.40965 16657.71745 16138.76205 5708.867 3353.284 3736.4647 2866.091 2867.1196 4040.55825 3947.4131 4433.9159 19442.3535 36197.699 44585.45587 3366.6697 4058.1161 5138.2567 3471.4096 5693.4305 4719.52405 17361.7661 4032.2407 18259.216 3645.0894 4237.12655 19521.9682 4527.18295 5325.651 3659.346 4149.736 36837.467 36950.2567 5428.7277 39241.442 18963.17192 40932.4295 4753.6368 4266.1658 3260.199 3756.6216 19199.944 4239.89265 5031.26955 6799.458 4243.59005 3761.292 4350.5144 4347.02335 5425.02335 4738.2682 5327.40025 38746.3551 4949.7587 58571.07448 4463.2051 3875.7341 32734.1863 17496.306 4454.40265 21472.4788 3866.8552 19719.6947 4562.8421 4357.04365 5152.134 4076.497 5148.5526 6128.79745 37607.5277 6334.34355 4673.3922 4667.60765 3989.841 3994.1778 16776.30405 21984.47061 4185.0979 5257.50795 4571.41305 19040.876 5261.46945 4779.6023 5375.038 6653.7886 12404.8791 55135.40209 38282.7495 4889.9995 5972.378 4795.6568 6666.243 11326.71487 6360.9936 4500.33925 27375.90478 4992.3764 4894.7533 18972.495 5385.3379 5002.7827 6184.2994 43943.8761 35491.64 14358.36437 5012.471 3935.1799 4518.82625 4320.41085 5124.1887 4536.259 5227.98875 4746.344 6414.178 20984.0936 20234.85475 5926.846 4751.07 5240.765 39983.42595 5245.2269 5246.047 5836.5204 39774.2763 4762.329 19496

Databricks visualization. Run in Databricks to view.

We can observe that only our bmi variable appears to have missing values when we look at the boxplots for our numerical variables. Due to the extreme unusualness of these values in our research, we decided to remove BMIs exceeding 50.

In [0]:
#We used the filter function to remove any bmi values more than 50 after examining the earlier boxplots.
Insurance_Train_drop = Insurance_Train.filter("bmi < 50")

In [0]:
# To determine the number of rows removed as a result of the bmi variable filter being explicitly mentioned

print("There were removed", Insurance_Train.count() - Insurance_Train_drop.count(), "rows!")
print("We were left with", Insurance_Train_drop.count(),"remaining rows!")

There were removed 2 rows!
We were left with 912 remaining rows!


##Feature Engineering

In [0]:
# In order to build dummy variables in advance, we are creating bmi categories.

def bmicat(bmi):
  
  if bmi < 18.5:
    return "Underweight"
  
  elif bmi >= 18.5 and bmi <= 24.9:
    return "Normal"
  
  elif bmi >= 25 and bmi <= 29.9:
    return "Overweight"
  
  else: 
    return "Obese"

To construct the BMI's categories, we made bins for the feature.

In [0]:
from pyspark.sql.functions import udf
from pyspark.sql.types import *

bin_udf = udf(bmicat, StringType() )

Insurance_Train = Insurance_Train_drop.withColumn("bmi_group", bin_udf("bmi"))
Insurance_Test = Insurance_Test.withColumn("bmi_group", bin_udf("bmi"))

Since our model cannot contain categorical variables, we must now encode this new variable. Initially, we believed that the BMI variable could be encoded using the StringIndex. However, after some thought, we realized that the dummy variables would be a better option because the values assigned in the StringIndex were out of order.

In [0]:
#Building dummy variables using the train dataset's bmi_group.

from pyspark.sql.functions import when
Insurance_Train = Insurance_Train.withColumn("Overweight", when(Insurance_Train.bmi_group == "Overweight", 1).otherwise(0))
Insurance_Train = Insurance_Train.withColumn("Obese", when(Insurance_Train.bmi_group == "Obese", 1).otherwise(0))
Insurance_Train = Insurance_Train.withColumn("Normal", when(Insurance_Train.bmi_group == "Normal", 1).otherwise(0))

In [0]:
# Creating those dummy variables from the test dataset's bmi_group.

Insurance_Test = Insurance_Test.withColumn("Overweight", when(Insurance_Test.bmi_group == "Overweight", 1).otherwise(0))
Insurance_Test = Insurance_Test.withColumn("Obese", when(Insurance_Test.bmi_group == "Obese", 1).otherwise(0))
Insurance_Test = Insurance_Test.withColumn("Normal", when(Insurance_Test.bmi_group == "Normal", 1).otherwise(0))

In [0]:
#Showing the test dataset to verify that the newly produced dummy variables were created correctly.
display(Insurance_Test)

age bmi children charges Smoker_Index Sex_Index bmi_group Overweight Obese Normal 18 17.29 2 12829.4551 1.0 0.0 Underweight 0 0 0 18 25.46 0 1708.0014 0.0 0.0 Overweight 1 0 0 18 27.36 1 17178.6824 1.0 0.0 Overweight 1 0 0 18 28.215 0 2200.83085 0.0 1.0 Overweight 1 0 0 18 28.5 0 1712.227 0.0 0.0 Overweight 1 0 0 18 30.03 1 1720.3537 0.0 0.0 Obese 0 1 0 18 31.35 4 4561.1885 0.0 1.0 Obese 0 1 0 18 31.92 0 2205.9808 0.0 1.0 Obese 0 1 0 18 33.33 0 1135.9407 0.0 0.0 Obese 0 1 0 18 33.88 0 11482.63485 0.0 1.0 Obese 0 1 0 18 35.2 1 1727.54 0.0 0.0 Obese 0 1 0 18 38.17 0 1631.6683 0.0 1.0 Obese 0 1 0 18 38.17 0 36307.7983 1.0 0.0 Obese 0 1 0 18 42.24 0 38792.6856 1.0 1.0 Obese 0 1 0 19 17.48 0 1621.3402 0.0 0.0 Underweight 0 0 0 19 20.3 0 1242.26 0.0 0.0 Normal 0 0 1 19 20.6 0 1731.677 0.0 1.0 Normal 0 0 1 19 20.7 0 1242.816 0.0 0.0 Normal 0 0 1 19 20.9 1 1832.094 0.0 0.0 Normal 0 0 1 19 21.755 0 1627.28245 0.0 0.0 Normal 0 0 1 19 24.6 1 1837.237 0.0 0.0 Normal 0 0 1 19 25.175 0 1632.03625 0.0 0.0 Overweight 1 0 0 19 25.555 0 1632.56445 0.0 0.0 Overweight 1 0 0 19 25.555 1 2221.56445 0.0 0.0 Overweight 1 0 0 19 26.03 1 16450.8947 1.0 0.0 Overweight 1 0 0 19 27.265 2 22493.65964 0.0 0.0 Overweight 1 0 0 19 27.7 0 16297.846 1.0 0.0 Overweight 1 0 0 19 27.9 0 16884.924 1.0 1.0 Overweight 1 0 0 19 27.93 3 18838.70366 0.0 1.0 Overweight 1 0 0 19 28.4 1 1842.519 0.0 0.0 Overweight 1 0 0 19 28.6 5 4687.797 0.0 1.0 Overweight 1 0 0 19 30.495 0 2128.43105 0.0 1.0 Obese 0 1 0 19 32.9 0 1748.774 0.0 1.0 Obese 0 1 0 19 34.1 0 1261.442 0.0 0.0 Obese 0 1 0 19 34.9 0 34828.654 1.0 0.0 Obese 0 1 0 19 36.575 0 2136.88225 0.0 1.0 Obese 0 1 0 19 36.955 0 36219.40545 1.0 0.0 Obese 0 1 0 19 44.88 0 39722.7462 1.0 0.0 Obese 0 1 0 20 21.8 0 20167.33603 1.0 1.0 Normal 0 0 1 20 22.0 1 1964.78 0.0 0.0 Normal 0 0 1 20 24.42 0 26125.67477 1.0 1.0 Normal 0 0 1 20 27.3 0 16232.847 1.0 0.0 Overweight 1 0 0 20 30.115 5 4915.05985 0.0 0.0 Obese 0 1 0 20 30.59 0 2459.7201 0.0 1.0 Obese 0 1 0 20 31.13 2 2566.4707 0.0 0.0 Obese 0 1 0 20 31.79 2 3056.3881 0.0 1.0 Obese 0 1 0 20 32.395 1 2362.22905 0.0 0.0 Obese 0 1 0 20 33.0 1 1980.07 0.0 0.0 Obese 0 1 0 20 35.31 1 27724.28875 0.0 0.0 Obese 0 1 0 20 39.4 2 38344.566 1.0 0.0 Obese 0 1 0 21 16.815 1 3167.45585 0.0 1.0 Underweight 0 0 0 21 22.135 0 2585.85065 0.0 1.0 Normal 0 0 1 21 22.3 1 2103.08 0.0 0.0 Normal 0 0 1 21 23.75 2 3077.0955 0.0 0.0 Normal 0 0 1 21 28.975 0 1906.35825 0.0 0.0 Overweight 1 0 0 21 31.02 0 16586.49771 0.0 0.0 Obese 0 1 0 21 31.1 0 1526.312 0.0 0.0 Obese 0 1 0 21 33.63 2 3579.8287 0.0 1.0 Obese 0 1 0 21 35.72 0 2404.7338 0.0 1.0 Obese 0 1 0 21 36.85 0 1534.3045 0.0 0.0 Obese 0 1 0 22 20.235 0 2527.81865 0.0 1.0 Normal 0 0 1 22 21.28 3 4296.2712 0.0 1.0 Normal 0 0 1 22 24.3 0 2150.469 0.0 1.0 Normal 0 0 1 22 25.175 0 2045.68525 0.0 0.0 Overweight 1 0 0 22 26.84 0 1664.9996 0.0 0.0 Overweight 1 0 0 22 28.82 0 2156.7518 0.0 1.0 Overweight 1 0 0 22 31.73 0 2254.7967 0.0 0.0 Obese 0 1 0 22 34.58 2 3925.7582 0.0 1.0 Obese 0 1 0 22 34.8 3 3443.064 0.0 0.0 Obese 0 1 0 22 39.805 0 2755.02095 0.0 1.0 Obese 0 1 0 23 18.715 0 21595.38229 0.0 0.0 Normal 0 0 1 23 23.18 2 14426.07385 0.0 1.0 Normal 0 0 1 23 24.51 0 2396.0959 0.0 0.0 Normal 0 0 1 23 28.0 0 13126.67745 0.0 1.0 Overweight 1 0 0 23 34.4 0 1826.843 0.0 0.0 Obese 0 1 0 23 35.2 1 2416.955 0.0 0.0 Obese 0 1 0 23 36.67 2 38511.6283 1.0 1.0 Obese 0 1 0 23 50.38 1 2438.0552 0.0 0.0 Obese 0 1 0 24 24.225 0 2842.76075 0.0 1.0 Normal 0 0 1 24 25.8 0 1972.95 0.0 0.0 Overweight 1 0 0 24 29.83 0 18648.4217 1.0 0.0 Overweight 1 0 0 24 29.925 0 2850.68375 0.0 1.0 Obese 0 1 0 24 30.21 3 4618.0799 0.0 1.0 Obese 0 1 0 24 31.065 0 34254.05335 1.0 0.0 Obese 0 1 0 24 32.01 0 1981.5819 0.0 0.0 Obese 0 1 0 24 32.7 0 34472.841 1.0 0.0 Obese 0 1 0 24 35.86 0 1986.9334 0.0 0.0 Obese 0 1 0 25 22.515 1 3594.17085 0.0 1.0 Normal 0 0 1 25 23.9 5 5080.096 0.0 0.0 Normal 0 0 1 25 24.13 0 15817.9857 1.0 0.0 Normal 0 0 1 25 26.22 0 2721.3208 0.0 0.0 Overweight 1 0 0 25 26.8 3 3906.


By now, we had eliminated several columns from our model that weren't required, such as "sex". But before moving on to our model and building the dummy variables, we must remove every last column that is not required. Therefore, bmi and bmi_group will be dropped.

In [0]:
#Once we have that information on the newly formed dummy variables, we are dropping the bmi and bmi_group variables from the test and train datasets using the drop function.

Insurance_Train = Insurance_Train.drop('bmi','bmi_group')

We need to drop all the remaining columns that will not be necessary. So we will drop bmi and bmi_group.

In [0]:
display(Insurance_Test)

age bmi children charges Smoker_Index Sex_Index bmi_group Overweight Obese Normal 18 17.29 2 12829.4551 1.0 0.0 Underweight 0 0 0 18 25.46 0 1708.0014 0.0 0.0 Overweight 1 0 0 18 27.36 1 17178.6824 1.0 0.0 Overweight 1 0 0 18 28.215 0 2200.83085 0.0 1.0 Overweight 1 0 0 18 28.5 0 1712.227 0.0 0.0 Overweight 1 0 0 18 30.03 1 1720.3537 0.0 0.0 Obese 0 1 0 18 31.35 4 4561.1885 0.0 1.0 Obese 0 1 0 18 31.92 0 2205.9808 0.0 1.0 Obese 0 1 0 18 33.33 0 1135.9407 0.0 0.0 Obese 0 1 0 18 33.88 0 11482.63485 0.0 1.0 Obese 0 1 0 18 35.2 1 1727.54 0.0 0.0 Obese 0 1 0 18 38.17 0 1631.6683 0.0 1.0 Obese 0 1 0 18 38.17 0 36307.7983 1.0 0.0 Obese 0 1 0 18 42.24 0 38792.6856 1.0 1.0 Obese 0 1 0 19 17.48 0 1621.3402 0.0 0.0 Underweight 0 0 0 19 20.3 0 1242.26 0.0 0.0 Normal 0 0 1 19 20.6 0 1731.677 0.0 1.0 Normal 0 0 1 19 20.7 0 1242.816 0.0 0.0 Normal 0 0 1 19 20.9 1 1832.094 0.0 0.0 Normal 0 0 1 19 21.755 0 1627.28245 0.0 0.0 Normal 0 0 1 19 24.6 1 1837.237 0.0 0.0 Normal 0 0 1 19 25.175 0 1632.03625 0.0 0.0 Overweight 1 0 0 19 25.555 0 1632.56445 0.0 0.0 Overweight 1 0 0 19 25.555 1 2221.56445 0.0 0.0 Overweight 1 0 0 19 26.03 1 16450.8947 1.0 0.0 Overweight 1 0 0 19 27.265 2 22493.65964 0.0 0.0 Overweight 1 0 0 19 27.7 0 16297.846 1.0 0.0 Overweight 1 0 0 19 27.9 0 16884.924 1.0 1.0 Overweight 1 0 0 19 27.93 3 18838.70366 0.0 1.0 Overweight 1 0 0 19 28.4 1 1842.519 0.0 0.0 Overweight 1 0 0 19 28.6 5 4687.797 0.0 1.0 Overweight 1 0 0 19 30.495 0 2128.43105 0.0 1.0 Obese 0 1 0 19 32.9 0 1748.774 0.0 1.0 Obese 0 1 0 19 34.1 0 1261.442 0.0 0.0 Obese 0 1 0 19 34.9 0 34828.654 1.0 0.0 Obese 0 1 0 19 36.575 0 2136.88225 0.0 1.0 Obese 0 1 0 19 36.955 0 36219.40545 1.0 0.0 Obese 0 1 0 19 44.88 0 39722.7462 1.0 0.0 Obese 0 1 0 20 21.8 0 20167.33603 1.0 1.0 Normal 0 0 1 20 22.0 1 1964.78 0.0 0.0 Normal 0 0 1 20 24.42 0 26125.67477 1.0 1.0 Normal 0 0 1 20 27.3 0 16232.847 1.0 0.0 Overweight 1 0 0 20 30.115 5 4915.05985 0.0 0.0 Obese 0 1 0 20 30.59 0 2459.7201 0.0 1.0 Obese 0 1 0 20 31.13 2 2566.4707 0.0 0.0 Obese 0 1 0 20 31.79 2 3056.3881 0.0 1.0 Obese 0 1 0 20 32.395 1 2362.22905 0.0 0.0 Obese 0 1 0 20 33.0 1 1980.07 0.0 0.0 Obese 0 1 0 20 35.31 1 27724.28875 0.0 0.0 Obese 0 1 0 20 39.4 2 38344.566 1.0 0.0 Obese 0 1 0 21 16.815 1 3167.45585 0.0 1.0 Underweight 0 0 0 21 22.135 0 2585.85065 0.0 1.0 Normal 0 0 1 21 22.3 1 2103.08 0.0 0.0 Normal 0 0 1 21 23.75 2 3077.0955 0.0 0.0 Normal 0 0 1 21 28.975 0 1906.35825 0.0 0.0 Overweight 1 0 0 21 31.02 0 16586.49771 0.0 0.0 Obese 0 1 0 21 31.1 0 1526.312 0.0 0.0 Obese 0 1 0 21 33.63 2 3579.8287 0.0 1.0 Obese 0 1 0 21 35.72 0 2404.7338 0.0 1.0 Obese 0 1 0 21 36.85 0 1534.3045 0.0 0.0 Obese 0 1 0 22 20.235 0 2527.81865 0.0 1.0 Normal 0 0 1 22 21.28 3 4296.2712 0.0 1.0 Normal 0 0 1 22 24.3 0 2150.469 0.0 1.0 Normal 0 0 1 22 25.175 0 2045.68525 0.0 0.0 Overweight 1 0 0 22 26.84 0 1664.9996 0.0 0.0 Overweight 1 0 0 22 28.82 0 2156.7518 0.0 1.0 Overweight 1 0 0 22 31.73 0 2254.7967 0.0 0.0 Obese 0 1 0 22 34.58 2 3925.7582 0.0 1.0 Obese 0 1 0 22 34.8 3 3443.064 0.0 0.0 Obese 0 1 0 22 39.805 0 2755.02095 0.0 1.0 Obese 0 1 0 23 18.715 0 21595.38229 0.0 0.0 Normal 0 0 1 23 23.18 2 14426.07385 0.0 1.0 Normal 0 0 1 23 24.51 0 2396.0959 0.0 0.0 Normal 0 0 1 23 28.0 0 13126.67745 0.0 1.0 Overweight 1 0 0 23 34.4 0 1826.843 0.0 0.0 Obese 0 1 0 23 35.2 1 2416.955 0.0 0.0 Obese 0 1 0 23 36.67 2 38511.6283 1.0 1.0 Obese 0 1 0 23 50.38 1 2438.0552 0.0 0.0 Obese 0 1 0 24 24.225 0 2842.76075 0.0 1.0 Normal 0 0 1 24 25.8 0 1972.95 0.0 0.0 Overweight 1 0 0 24 29.83 0 18648.4217 1.0 0.0 Overweight 1 0 0 24 29.925 0 2850.68375 0.0 1.0 Obese 0 1 0 24 30.21 3 4618.0799 0.0 1.0 Obese 0 1 0 24 31.065 0 34254.05335 1.0 0.0 Obese 0 1 0 24 32.01 0 1981.5819 0.0 0.0 Obese 0 1 0 24 32.7 0 34472.841 1.0 0.0 Obese 0 1 0 24 35.86 0 1986.9334 0.0 0.0 Obese 0 1 0 25 22.515 1 3594.17085 0.0 1.0 Normal 0 0 1 25 23.9 5 5080.096 0.0 0.0 Normal 0 0 1 25 24.13 0 15817.9857 1.0 0.0 Normal 0 0 1 25 26.22 0 2721.3208 0.0 0.0 Overweight 1 0 0 25 26.8 3 3906.

In [0]:
display(Insurance_Train)

age children charges Smoker_Index Sex_Index Overweight Obese Normal 18 0 1694.7964 0.0 0.0 0 0 0 18 0 1607.5101 0.0 1.0 0 0 1 18 0 1702.4553 0.0 0.0 0 0 1 18 0 13747.87235 1.0 0.0 0 0 1 18 0 14283.4594 1.0 1.0 0 0 1 18 2 11884.04858 0.0 0.0 0 0 1 18 0 1704.5681 0.0 0.0 0 0 1 18 0 1704.70015 0.0 0.0 0 0 1 18 0 1121.8739 0.0 0.0 0 0 1 18 1 1711.0268 0.0 0.0 0 0 1 18 0 1705.6245 0.0 0.0 0 0 1 18 1 2201.0971 0.0 1.0 0 0 1 18 0 2196.4732 0.0 1.0 1 0 0 18 0 15518.18025 1.0 0.0 1 0 0 18 0 1708.92575 0.0 0.0 1 0 0 18 2 2304.0022 0.0 0.0 1 0 0 18 0 2198.18985 0.0 1.0 1 0 0 18 0 1615.7667 0.0 1.0 1 0 0 18 3 18223.4512 1.0 1.0 1 0 0 18 1 11272.33139 0.0 0.0 1 0 0 18 0 7323.734819 0.0 1.0 1 0 0 18 1 1719.4363 0.0 0.0 1 0 0 18 0 2203.47185 0.0 1.0 0 1 0 18 0 21344.8467 0.0 1.0 0 1 0 18 0 1131.5066 0.0 0.0 0 1 0 18 0 2203.73595 0.0 1.0 0 1 0 18 3 3481.868 0.0 0.0 0 1 0 18 0 1621.8827 0.0 1.0 0 1 0 18 0 1622.1885 0.0 1.0 0 1 0 18 2 34303.1672 1.0 0.0 0 1 0 18 0 33732.6867 1.0 0.0 0 1 0 18 2 2801.2588 0.0 1.0 0 1 0 18 0 2207.69745 0.0 1.0 0 1 0 18 0 34617.84065 1.0 0.0 0 1 0 18 0 1136.3994 0.0 0.0 0 1 0 18 1 1725.5523 0.0 0.0 0 1 0 18 0 1137.011 0.0 0.0 0 1 0 18 0 1137.4697 0.0 0.0 0 1 0 18 0 2211.13075 0.0 1.0 0 1 0 18 0 1629.8335 0.0 1.0 0 1 0 18 0 36149.4835 1.0 1.0 0 1 0 18 0 1141.4451 0.0 0.0 0 1 0 18 1 2219.4451 0.0 1.0 0 1 0 18 0 1631.8212 0.0 1.0 0 1 0 18 0 14133.03775 0.0 1.0 0 1 0 18 2 3393.35635 0.0 1.0 0 1 0 18 0 12890.05765 0.0 0.0 0 1 0 18 0 1633.0444 0.0 1.0 0 1 0 18 0 1633.9618 0.0 1.0 0 1 0 18 0 2217.46915 0.0 1.0 0 1 0 18 0 1634.5734 0.0 1.0 0 1 0 18 0 2217.6012 0.0 1.0 0 1 0 18 0 1146.7966 0.0 0.0 0 1 0 18 0 1149.3959 0.0 0.0 0 1 0 19 0 1727.785 0.0 1.0 0 0 0 19 0 1728.897 0.0 1.0 0 0 1 19 0 1241.565 0.0 0.0 0 0 1 19 0 1625.43375 0.0 0.0 0 0 1 19 2 2803.69785 0.0 0.0 0 0 1 19 0 13844.506 1.0 1.0 0 0 1 19 0 2117.33885 0.0 1.0 0 0 1 19 0 1628.4709 0.0 0.0 0 0 1 19 2 2913.569 0.0 1.0 0 0 1 19 1 2709.1119 0.0 1.0 0 0 1 19 1 2709.24395 0.0 1.0 0 0 1 19 0 1737.376 0.0 1.0 0 0 1 19 1 2710.82855 0.0 1.0 1 0 0 19 0 1252.407 0.0 0.0 1 0 0 19 0 1635.73365 0.0 0.0 1 0 0 19 0 17081.08 1.0 1.0 1 0 0 19 0 17468.9839 1.0 1.0 1 0 0 19 1 2331.519 0.0 1.0 1 0 0 19 0 1253.936 0.0 0.0 1 0 0 19 0 17748.5062 1.0 1.0 1 0 0 19 0 1743.214 0.0 1.0 1 0 0 19 0 17352.6803 1.0 0.0 1 0 0 19 0 1744.465 0.0 1.0 1 0 0 19 0 33307.5508 1.0 1.0 0 1 0 19 0 32548.3405 1.0 0.0 0 1 0 19 0 1256.299 0.0 0.0 0 1 0 19 0 1639.5631 0.0 0.0 0 1 0 19 0 1639.5631 0.0 0.0 0 1 0 19 2 24059.68019 0.0 1.0 0 1 0 19 1 2719.27975 0.0 1.0 0 1 0 19 0 33750.2918 1.0 0.0 0 1 0 19 0 2130.6759 0.0 1.0 0 1 0 19 0 36898.73308 1.0 1.0 0 1 0 19 0 23082.95533 0.0 0.0 0 1 0 19 0 34439.8559 1.0 1.0 0 1 0 19 0 1261.859 0.0 0.0 0 1 0 19 2 36397.576 1.0 1.0 0 1 0 19 0 34779.615 1.0 0.0 0 1 0 19 0 2134.9015 0.0 1.0 0 1 0 19 0 1263.249 0.0 0.0 0 1 0 19 0 1646.4297 0.0 0.0 0 1 0 19 0 2138.0707 0.0 1.0 0 1 0 19 1 2730.10785 0.0 1.0 0 1 0 19 0 1759.338 0.0 1.0 0 1 0 20 0 14711.7438 1.0 1.0 0 0 1 20 1 17085.2676 1.0 1.0 1 0 0 20 0 1967.0227 0.0 0.0 1 0 0 20 1 17560.37975 1.0 0.0 1 0 0 20 0 2457.21115 0.0 1.0 1 0 0 20 0 2257.47525 0.0 1.0 1 0 0 20 0 1875.344 0.0 1.0 1 0 0 20 0 1769.53165 0.0 0.0 1 0 0 20 0 33475.81715 1.0 0.0 0 1 0 20 0 1877.9294 0.0 1.0 0 1 0 20 0 2261.5688 0.0 1.0 0 1 0 20 0 1880.07 0.0 1.0 0 1 0 20 0 1880.487 0.0 1.0 0 1 0 20 0 1391.5287 0.0 0.0 0 1 0 20 3 37465.34375 1.0 0.0 0 1 0 20 5 4830.63 0.0 1.0 0 1 0 20 0 1984.4533 0.0 0.0 0 1 0 21 1 2585.269 0.0 1.0 0 0 0 21 3 3861.20965 0.0 0.0 0 0 1 21 1 15359.1045 1.0 1.0 0 0 1 21 2 3180.5101 0.0 1.0 0 0 1 21 0 1515.3449 0.0 0.0 0 0 1 21 4 17942.106 1.0 0.0 1 0 0 21 2 3279.86855 0.0 0.0 1 0 0 21 0 2007.945 0.0 1.0 1 0 0 21 0 2102.2647 0.0 0.0 1 0 0 21 1 2597.779 0.0 1.0 1 0 0 21 0 2104.1134 0.0 0.0 1 0 0 21 0 1909.52745 0.0 0.0 0 1 0 21 2 26018.95052 0.0 1.0 0 1 0 21 0 2020.177 0.0 1.0 0 1 0 21 0 2020.5523 0.0 1.0 0 1 0 21 0 1532.4697 0.0 0.0 0 1 0 21 0 1917.3184 0.0 0.0 0 1 0 21 0 2026.9741 0.0 1.0 0 1 0 22 3 4005.4225 0.0 0.0 0 0 1 22 0

We will scale the data in both the training and testing datasets now that we are almost ready to run the regression since we think this will help us get better results. Nevertheless, we choose not to scale the target variable, even though it is not incorrect.

###Training Dataset

In [0]:
# To assist us in scaling the variables, we are importing the necessary libraries. First, the column type will be changed from vector to double by the UDF. With the exception of the target variable, we are then producing new, scaled columns for each of the preceding columns using the for loop. We are applying some of the changes we learnt in class to this 'for' loop, such as creating the pipeline with the assembler and scaler stages, the assembler, and the scaler (using the StandartScaler, but other scalers may have been used). We will next add the scaled columns to the training dataset using the pipeline.


from pyspark.ml.feature import StandardScaler
from pyspark.ml import Pipeline
from pyspark.sql.functions import udf
from pyspark.sql.types import DoubleType
 

unlist = udf(lambda x: float(list(x)[0]), DoubleType())
 

for i in ["age","children","Smoker_Index","Sex_Index","Overweight","Obese","Normal"]:

    assembler = VectorAssembler(inputCols=[i],outputCol=i+"_Vect")
 

    scaler = StandardScaler(inputCol=i+"_Vect", outputCol=i+"_Scaled")
 

    pipeline = Pipeline(stages=[assembler, scaler])
 

    Insurance_Train = pipeline.fit(Insurance_Train).transform(Insurance_Train).withColumn(i+"_Scaled", unlist(i+"_Scaled")).drop(i+"_Vect")
 
print("After Scaling :")
Insurance_Train.head(10)

After Scaling :
Out[309]: [Row(age=18, children=0, charges=1694.7964, Smoker_Index=0.0, Sex_Index=0.0, Overweight=0, Obese=0, Normal=0, age_Scaled=1.2843017578171065, children_Scaled=0.0, Smoker_Index_Scaled=0.0, Sex_Index_Scaled=0.0, Overweight_Scaled=0.0, Obese_Scaled=0.0, Normal_Scaled=0.0),
 Row(age=18, children=0, charges=1607.5101, Smoker_Index=0.0, Sex_Index=1.0, Overweight=0, Obese=0, Normal=1, age_Scaled=1.2843017578171065, children_Scaled=0.0, Smoker_Index_Scaled=0.0, Sex_Index_Scaled=1.9994850526833277, Overweight_Scaled=0.0, Obese_Scaled=0.0, Normal_Scaled=2.7332221057975796),
 Row(age=18, children=0, charges=1702.4553, Smoker_Index=0.0, Sex_Index=0.0, Overweight=0, Obese=0, Normal=1, age_Scaled=1.2843017578171065, children_Scaled=0.0, Smoker_Index_Scaled=0.0, Sex_Index_Scaled=0.0, Overweight_Scaled=0.0, Obese_Scaled=0.0, Normal_Scaled=2.7332221057975796),
 Row(age=18, children=0, charges=13747.87235, Smoker_Index=1.0, Sex_Index=0.0, Overweight=0, Obese=0, Normal=1, age_Sca

###Test Dataset

In [0]:
# In this instance, we are replicating the procedures from the preceding section, albeit in the Test dataset.

unlist = udf(lambda x: float(list(x)[0]), DoubleType())
 

for i in ["age","children","Smoker_Index","Sex_Index","Overweight","Obese","Normal"]:

    assembler = VectorAssembler(inputCols=[i],outputCol=i+"_Vect")
 

    scaler = StandardScaler(inputCol=i+"_Vect", outputCol=i+"_Scaled")
 

    pipeline = Pipeline(stages=[assembler, scaler])
 

    Insurance_Test = pipeline.fit(Insurance_Test).transform(Insurance_Test).withColumn(i+"_Scaled", unlist(i+"_Scaled")).drop(i+"_Vect")
 
print("After Scaling :")
Insurance_Test.head(10)

After Scaling :
Out[310]: [Row(age=18, bmi=17.29, children=2, charges=12829.4551, Smoker_Index=1.0, Sex_Index=0.0, bmi_group='Underweight', Overweight=0, Obese=0, Normal=0, age_Scaled=1.2755886799782168, children_Scaled=1.5943392959925058, Smoker_Index_Scaled=2.5652519050316624, Sex_Index_Scaled=0.0, Overweight_Scaled=0.0, Obese_Scaled=0.0, Normal_Scaled=0.0),
 Row(age=18, bmi=25.46, children=0, charges=1708.0014, Smoker_Index=0.0, Sex_Index=0.0, bmi_group='Overweight', Overweight=1, Obese=0, Normal=0, age_Scaled=1.2755886799782168, children_Scaled=0.0, Smoker_Index_Scaled=0.0, Sex_Index_Scaled=0.0, Overweight_Scaled=2.234554715877654, Obese_Scaled=0.0, Normal_Scaled=0.0),
 Row(age=18, bmi=27.36, children=1, charges=17178.6824, Smoker_Index=1.0, Sex_Index=0.0, bmi_group='Overweight', Overweight=1, Obese=0, Normal=0, age_Scaled=1.2755886799782168, children_Scaled=0.7971696479962529, Smoker_Index_Scaled=2.5652519050316624, Sex_Index_Scaled=0.0, Overweight_Scaled=2.234554715877654, Obese_

In [0]:
#We removed the original columns from the train and test datasets after scailing every variable in each dataset.

Insurance_Train = Insurance_Train.drop('age','children','Smoker_Index',
                                       'Sex_Index', 'Overweight', 'Obese',
                                       'Normal')
Insurance_Test = Insurance_Test.drop('age','children','Smoker_Index',
                                      'Sex_Index', 'Overweight', 'Obese',
                                      'Normal')

Once we only needed the scaled variables and the target on both datasets, we removed the non-scaled variables.

###Applying the Regression

In [0]:
# The features are being vectorized.

lrAssembler = VectorAssembler(inputCols=Insurance_Train.drop("charges").columns, outputCol="features")

In [0]:
#Here, we are configuring the model to perform the Linear Regression on the target variable.

lr = LinearRegression(labelCol="charges")

In [0]:
# Chain Vectorized features and Linear Regression into a Pipeline
pipeline = Pipeline(stages=[lrAssembler,lr])

# Train Model
lrModel = pipeline.fit(Insurance_Train)

# Predictions
lrPredictions = lrModel.transform(Insurance_Test)

# Display the Predictions
display(lrPredictions.select("charges","prediction","features"))

charges prediction features 12829.4551 25425.150720477686 Map(vectorType -> sparse, length -> 7, indices -> List(0, 1, 2), values -> List(1.2755886799782168, 1.5943392959925058, 2.5652519050316624)) 1708.0014 67.68845309631433 Map(vectorType -> sparse, length -> 7, indices -> List(0, 4), values -> List(1.2755886799782168, 2.234554715877654)) 17178.6824 25975.505393494946 Map(vectorType -> dense, length -> 7, values -> List(1.2755886799782168, 0.7971696479962529, 2.5652519050316624, 0.0, 2.234554715877654, 0.0, 0.0)) 2200.83085 86.9201489845318 Map(vectorType -> sparse, length -> 7, indices -> List(0, 3, 4), values -> List(1.2755886799782168, 2.0040938953260574, 2.234554715877654)) 1712.227 67.68845309631433 Map(vectorType -> sparse, length -> 7, indices -> List(0, 4), values -> List(1.2755886799782168, 2.234554715877654)) 1720.3537 4640.892410092696 Map(vectorType -> sparse, length -> 7, indices -> List(0, 1, 5), values -> List(1.2755886799782168, 0.7971696479962529, 1.9998661983607802)) 4561.1885 6151.4005835251955 Map(vectorType -> dense, length -> 7, values -> List(1.2755886799782168, 3.1886785919850116, 0.0, 2.0040938953260574, 0.0, 1.9998661983607802, 0.0)) 2205.9808 4163.031946799485 Map(vectorType -> sparse, length -> 7, indices -> List(0, 3, 5), values -> List(1.2755886799782168, 2.0040938953260574, 1.9998661983607802)) 1135.9407 4143.800250911268 Map(vectorType -> sparse, length -> 7, indices -> List(0, 5), values -> List(1.2755886799782168, 1.9998661983607802)) 11482.63485 4163.031946799485 Map(vectorType -> sparse, length -> 7, indices -> List(0, 3, 5), values -> List(1.2755886799782168, 2.0040938953260574, 1.9998661983607802)) 1727.54 4640.892410092696 Map(vectorType -> sparse, length -> 7, indices -> List(0, 1, 5), values -> List(1.2755886799782168, 0.7971696479962529, 1.9998661983607802)) 1631.6683 4163.031946799485 Map(vectorType -> sparse, length -> 7, indices -> List(0, 3, 5), values -> List(1.2755886799782168, 2.0040938953260574, 1.9998661983607802)) 36307.7983 29554.52503212847 Map(vectorType -> sparse, length -> 7, indices -> List(0, 2, 5), values -> List(1.2755886799782168, 2.5652519050316624, 1.9998661983607802)) 38792.6856 29573.75672801669 Map(vectorType -> dense, length -> 7, values -> List(1.2755886799782168, 0.0, 2.5652519050316624, 2.0040938953260574, 0.0, 1.9998661983607802, 0.0)) 1621.3402 -716.0844395705681 Map(vectorType -> sparse, length -> 7, indices -> List(0), values -> List(1.3464547177547843)) 1242.26 -700.4259046433426 Map(vectorType -> sparse, length -> 7, indices -> List(0, 6), values -> List(1.3464547177547843, 2.5908544278706893)) 1731.677 -681.1942087551251 Map(vectorType -> sparse, length -> 7, indices -> List(0, 3, 6), values -> List(1.3464547177547843, 2.0040938953260574, 2.5908544278706893)) 1242.816 -700.4259046433426 Map(vectorType -> sparse, length -> 7, indices -> List(0, 6), values -> List(1.3464547177547843, 2.5908544278706893)) 1832.094 -203.333745461915 Map(vectorType -> sparse, length -> 7, indices -> List(0, 1, 6), values -> List(1.3464547177547843, 0.7971696479962529, 2.5908544278706893)) 1627.28245 -700.4259046433426 Map(vectorType -> sparse, length -> 7, indices -> List(0, 6), values -> List(1.3464547177547843, 2.5908544278706893)) 1837.237 -203.333745461915 Map(vectorType -> sparse, length -> 7, indices -> List(0, 1, 6), values -> List(1.3464547177547843, 0.7971696479962529, 2.5908544278706893)) 1632.03625 331.36239262811796 Map(vectorType -> sparse, length -> 7, indices -> List(0, 4), values -> List(1.3464547177547843, 2.234554715877654)) 1632.56445 331.36239262811796 Map(vectorType -> sparse, length -> 7, indices -> List(0, 4), values -> List(1.3464547177547843, 2.234554715877654)) 2221.56445 828.4545518095456 Map(vectorType -> sparse, length -> 7, indices -> List(0, 1, 4), values -> List(1.3464547177547843, 0.7971696479962529, 2.234554715877654)) 16450.8947 26239.179333026746 Map(vectorType -> dense, length -> 7, values -> List(1.3464547177547843, 0.7971696479962

In [0]:
#In this case, we are printing the coefficients for linear regression and intercepting them.
print("Coefficients:")
coefficients = lrModel.stages[1].coefficients
i=0
for feature in Insurance_Train.drop("charges").columns:
  print(feature,":",coefficients[i])
  i+=1
print()
print("Coefficients List: %s" % str(lrModel.stages[1].coefficients))
print("Intercept: %s" % str(lrModel.stages[1].intercept))

Coefficients:
age_Scaled : 3720.737715901902
children_Scaled : 623.5713570265837
Smoker_Index_Scaled : 9905.74248531883
Sex_Index_Scaled : 9.596205014679807
Overweight_Scaled : 468.7496908247716
Obese_Scaled : 2561.950711609227
Normal_Scaled : 6.043772571234061

Coefficients List: [3720.737715901902,623.5713570265837,9905.74248531883,9.596205014679807,468.7496908247716,2561.950711609227,6.043772571234061]
Intercept: -5725.889290674844


In [0]:
# By acquiring the summary, we are able to examine our model's performance in more detail.
trainingSummary = lrModel.stages[1].summary
print("RMSE: %f" % trainingSummary.rootMeanSquaredError)
print("R2  : %f" % trainingSummary.r2)
trainingSummary.residuals.show()

RMSE: 5923.360942
R2  : 0.771130
+------------------+
|         residuals|
+------------------+
|2642.1357017656255|
|2519.1429604821783|
|2633.2756289715157|
|-9513.796430478234|
|-8997.396848967572|
|11760.413961993645|
|2635.3884289715156|
|2635.5204789715153|
|2052.6942289715157|
|2114.6196554825806|
|2636.4448289715156|
| 2585.502486993243|
|2086.8884430226585|
|-8764.706147937753|
| 1618.528461511996|
|1159.1499645341255|
| 2088.605093022659|
|1506.1819430226585|
|-7660.305086893899|
|10654.706628023061|
+------------------+
only showing top 20 rows



Our R2 is relatively high, but there are a lot of other possible explanations for its high value. Nonetheless, we believe that the necessary dataset adjustments were appropriately carried out, enabling us to obtain these outcomes. We also attempted to use regression analysis to the data in which we also sailed the target variable, but the outcomes were so poor that we abandoned the plan to scaile the target charges.

# PART C:

## <span style="color:blue"> **Show us what you got! (2 points):** </span>

<img src ='https://media.tenor.com/images/d8f45316e96078d93b36374474b67bf6/tenor.png'>

##### a) Using the cleaned e-commerce dataset from Part A, search for interesting variables that could be related to the countries' purchases. You should obtain the data regarding the countries' characteristics from the Macroeconomics sector of Pordata https://www.pordata.pt/en/Theme/Europe/Macroeconomics-32

###### You should limit your analysis to no more than six countries of your choice from the e-commerce dataset.

- The idea is that you find a way to associate some variables from Pordata and the purchases dataset. Ask yourselves the following questions: **What can explain/contribute to the fact that some countries buy more? or less? What can be related to the number of sales? Or the total value of sales?**... The questions are endless! Try to be creative and look for some associations!

###### You will be evaluated based on the logic used to solve this problem, the "investigation questions" you raise, the adequacy of your methodologies and your creativity.

##### MAKE SURE YOU COMMENT YOUR LOGIC AND "TELL YOUR STORY". WHAT QUESTIONS DID YOU RAISE? HOW DID YOU SEEK TO ANSWER THEM?

### Introduction

We used the data_parse dataset for this portion of the research, which had been carefully cleaned put through a number of transformations. One of them was that we removed all the information pertaining to 2011, thus it's crucial to note that this research will only use information from 2010. We do, however, note that we only have a small amount of 2010 data, and we think it might be a drawback. This analysis may be somewhat biased when compared to the Pordata indicators, which represent numbers for an entire year.

In [0]:
# To make analysis easier, we're going to present the data_parse dataset here as it was initially used in this project.
data_parse.head(10)

Out[317]: [Row(InvoiceNo='536365', StockCode='85123A', Description='WHITE HANGING HEART T-LIGHT HOLDER', Quantity=6, UnitPrice=2.55, CustomerID=17850, Country='United Kingdom', amount_spent=15.3, Year=2010, Month=12, Day=1, Hour=8),
 Row(InvoiceNo='536365', StockCode='71053', Description='WHITE METAL LANTERN', Quantity=6, UnitPrice=3.39, CustomerID=17850, Country='United Kingdom', amount_spent=20.34, Year=2010, Month=12, Day=1, Hour=8),
 Row(InvoiceNo='536365', StockCode='84406B', Description='CREAM CUPID HEARTS COAT HANGER', Quantity=8, UnitPrice=2.75, CustomerID=17850, Country='United Kingdom', amount_spent=22.0, Year=2010, Month=12, Day=1, Hour=8),
 Row(InvoiceNo='536365', StockCode='84029G', Description='KNITTED UNION FLAG HOT WATER BOTTLE', Quantity=6, UnitPrice=3.39, CustomerID=17850, Country='United Kingdom', amount_spent=20.34, Year=2010, Month=12, Day=1, Hour=8),
 Row(InvoiceNo='536365', StockCode='84029E', Description='RED WOOLLY HOTTIE WHITE HEART.', Quantity=6, UnitPrice=3.

In [0]:
# To facilitate the execution of SQL queries that will enable us to more easily arrange and present the data, we are generating a temporary view of our dataset.

data_parse.createOrReplaceTempView("Country_data")

In [0]:
# As previously said, in order to make analysis easier, we will carry out a few alternative visualizations. In this case, we are building a new dataframe and adding some of the original dataset's columns to it. 
# We are including the following columns in the dataset:
# - The Countries;
# - The sum of the amount_spent as Total_Amount;
# - The InvoiceNo as Total_Orders;
# - The sum of Quantity as the Amount_of_Products_Sold;
# - A count of the dinstinct customer as Total_Customers;
# - The Year
# After realizing that some countries were "Unspecified," we made the decision to exclude them and noted as much in the where clause. We divided up by nation as well.

Countries_data = spark.sql("SELECT Country, \
ROUND(SUM(amount_spent),2) AS Total_Amount, \
COUNT(DISTINCT InvoiceNo) AS Total_Orders, \
SUM(Quantity) AS Amount_of_Products_Sold, \
COUNT(DISTINCT CustomerID) AS Total_Customers, \
Year \
FROM Country_data \
WHERE  Country != 'Unspecified' \
GROUP BY Country, Year")
                          
                          
                          
                          
display(Countries_data)

Country Total_Amount Total_Orders Amount_of_Products_Sold Total_Customers Year Channel Islands 363.53 1 80 1 2010 Norway 3787.12 2 3582 1 2010 Switzerland 1304.92 2 714 2 2010 Lithuania 1661.06 4 652 1 2010 Belgium 1809.91 5 1755 4 2010 EIRE 8813.88 15 5253 3 2010 Austria 277.2 1 51 1 2010 Australia 1032.85 3 467 2 2010 Japan 7705.07 3 4093 3 2010 Poland 248.16 1 140 1 2010 Denmark 1281.5 1 454 1 2010 United Kingdom 498661.85 1291 267771 815 2010 Germany 15241.14 30 6878 18 2010 Cyprus 1590.82 1 917 1 2010 Iceland 711.79 1 319 1 2010 Italy 811.5 2 295 2 2010 Portugal 2439.97 6 984 6 2010 Spain 1843.73 4 867 4 2010 Finland 892.8 1 1254 1 2010 France 9616.31 21 4989 15 2010 Netherlands 8784.48 3 6811 2 2010 Sweden 3834.3 2 3954 1 2010

We chose to remove the strange characters Unspecified that appeared as we were writing our code from our study.

In [0]:
# As previously said, a temporary view is being created.
Countries_data.createOrReplaceTempView("Country_data1")

In [0]:
# We are building a new dataframe with a few new columns that we believe may be worthwhile to examine.These columns are:
# - Total_Amount/Total_Orders as AVG_Amount_Order;
# - Total_Amount/Total_Customers as AVG_Amount_Customers

Countries_detail = spark.sql(" SELECT * ,\
ROUND(Total_Amount/Total_Orders,2) AS AVG_Amount_Order, \
ROUND(Total_Amount/Total_Customers,2) AS AVG_Amount_Customer \
FROM Country_data1 ")                      
                          
                                       
display(Countries_detail)

Country Total_Amount Total_Orders Amount_of_Products_Sold Total_Customers Year AVG_Amount_Order AVG_Amount_Customer Channel Islands 363.53 1 80 1 2010 363.53 363.53 Norway 3787.12 2 3582 1 2010 1893.56 3787.12 Switzerland 1304.92 2 714 2 2010 652.46 652.46 Lithuania 1661.06 4 652 1 2010 415.27 1661.06 Belgium 1809.91 5 1755 4 2010 361.98 452.48 EIRE 8813.88 15 5253 3 2010 587.59 2937.96 Austria 277.2 1 51 1 2010 277.2 277.2 Australia 1032.85 3 467 2 2010 344.28 516.43 Japan 7705.07 3 4093 3 2010 2568.36 2568.36 Poland 248.16 1 140 1 2010 248.16 248.16 Denmark 1281.5 1 454 1 2010 1281.5 1281.5 United Kingdom 498661.85 1291 267771 815 2010 386.26 611.86 Germany 15241.14 30 6878 18 2010 508.04 846.73 Cyprus 1590.82 1 917 1 2010 1590.82 1590.82 Iceland 711.79 1 319 1 2010 711.79 711.79 Italy 811.5 2 295 2 2010 405.75 405.75 Portugal 2439.97 6 984 6 2010 406.66 406.66 Spain 1843.73 4 867 4 2010 460.93 460.93 Finland 892.8 1 1254 1 2010 892.8 892.8 France 9616.31 21 4989 15 2010 457.92 641.09 Netherlands 8784.48 3 6811 2 2010 2928.16 4392.24 Sweden 3834.3 2 3954 1 2010 1917.15 3834.3

### Countries Data Analysis

Here, we'll concentrate on analyzing each nation's performance in relation to the variables we previously constructed. In order to assist us in deciding which countries we should analyze using the data from PorData, we continued to identify which ones were the best and worst performing while analyzing each variable.

#####Total Amount

In [0]:
# In order to clearly see which country spent the most and the least, we are developing visuals for the Total_Amount per Country.Sorting is done on two graphs: one in ascending order and the other in descending order. Since we are only examining a maximum of six countries, we restricted the view to only display six.

display(Countries_detail.select("Country", "Total_Amount").sort(Countries_detail.Total_Amount.desc()).limit(6))
display(Countries_detail.select("Country", "Total_Amount").sort(Countries_detail.Total_Amount.asc()).limit(6))

Country Total_Amount United Kingdom 498661.85 Germany 15241.14 France 9616.31 EIRE 8813.88 Netherlands 8784.48 Japan 7705.07

Databricks visualization. Run in Databricks to view.

Country Total_Amount Poland 248.16 Austria 277.2 Channel Islands 363.53 Iceland 711.79 Italy 811.5 Finland 892.8

Databricks visualization. Run in Databricks to view.

**Through the bar charts we can tell that that the countries with the highest total of sales were:**

United Kingdom, Germany, France, EIRE, Netherlands and Japan

**On the other hand the countries with the lowest total of sales were:**

Poland, Austria, Channel Islands, Iceland, Italy and Finland

#####Total Orders

In [0]:
# Here, we are visualizing the Total Orders, just as we did in the previous cell. Since we are only examining a maximum of six countries, we restricted the view to only display six.

display(Countries_detail.select("Country", "Total_Orders").sort(Countries_detail.Total_Orders.desc()).limit(6))

display(Countries_detail.select("Country", "Total_Orders").sort(Countries_detail.Total_Orders.asc()).limit(6))

Country Total_Orders United Kingdom 1291 Germany 30 France 21 EIRE 15 Portugal 6 Belgium 5

Databricks visualization. Run in Databricks to view.

Country Total_Orders Austria 1 Cyprus 1 Channel Islands 1 Denmark 1 Poland 1 Iceland 1

**Through the table we can tell that the countries with the highest total orders were:**

United Kingdom, Germany , France, EIRE, Portugal and Belgium

**On the other hand the countries with the lowest total of orders were:**

Austria, Cyprus, Channel Islands, Denmark, Poland and Iceland

#####Amount of Product Sold

In [0]:
#Similar to what we did in the previous cell, we are visualizing the Amount_of_Product_Sold in this one. Since we are only examining a maximum of six countries, we restricted the view to only display six.

display(Countries_detail.select("Country", "Amount_of_Products_Sold").sort(Countries_detail.Amount_of_Products_Sold.desc()).limit(6))

display(Countries_detail.select("Country", "Amount_of_Products_Sold").sort(Countries_detail.Amount_of_Products_Sold.asc()).limit(6))

Country Amount_of_Products_Sold United Kingdom 267771 Germany 6878 Netherlands 6811 EIRE 5253 France 4989 Japan 4093

Databricks visualization. Run in Databricks to view.

Country Amount_of_Products_Sold Austria 51 Channel Islands 80 Poland 140 Italy 295 Iceland 319 Denmark 454

Databricks visualization. Run in Databricks to view.

**Through the table we can tell that the countries with the highest Amount of Products were:**

United Kingdom, Germany, Netherlands, EIRE, France and Japan

**On the other hand the countries with the lowest Amount of Products were:**

Austria, Channel Islands, Poland, Italy, Iceland and Denmark



#####Total Customers

In [0]:
# Here, we are visualizing the Total_Customers instead of the previous cell as we did in the previous cell. Since we are only examining a maximum of six countries, we restricted the view to only display six.

display(Countries_detail.select("Country", "Total_Customers").sort(Countries_detail.Total_Customers.desc()).limit(6))

display(Countries_detail.select("Country", "Total_Customers").sort(Countries_detail.Total_Customers.asc()).limit(6))

Country Total_Customers United Kingdom 815 Germany 18 France 15 Portugal 6 Belgium 4 Spain 4

Databricks visualization. Run in Databricks to view.

Country Total_Customers Austria 1 Cyprus 1 Norway 1 Poland 1 Lithuania 1 Denmark 1

**Through the bar chart we can tell that the countries with the highest Amount of Customers were:**

United Kingdom, Germany, France, Portugal, Belgium and Spain

**On the other hand the countries with the lowest Amount of Customers were:**

Austria, Cyprus, Norway, Poland, Lithuania and Denmark

#####Average Amount Order

In [0]:
#Here, we choose to analyze the AVG_Amount_Order and restricted the view to six nations by selecting the doughnut pie chart visual.

display(Countries_detail.select("Country", "AVG_Amount_Order").sort(Countries_detail.AVG_Amount_Order.desc()).limit(6))

display(Countries_detail.select("Country", "AVG_Amount_Order").sort(Countries_detail.AVG_Amount_Order.asc()).limit(6))

Country AVG_Amount_Order Netherlands 2928.16 Japan 2568.36 Sweden 1917.15 Norway 1893.56 Cyprus 1590.82 Denmark 1281.5

Databricks visualization. Run in Databricks to view.

Country AVG_Amount_Order Poland 248.16 Austria 277.2 Australia 344.28 Belgium 361.98 Channel Islands 363.53 United Kingdom 386.26

Databricks visualization. Run in Databricks to view.

**Through the pie chart we can tell that the countries with the highest AVG_Amount_Order were:**

Netherlands, Japan, Sweden, Norway, Cyprus and Denmark

**On the other hand the countries with the lowest Amount of AVG_Amount_Order were:**

Poland, Austria, Belgium, Channel Islands and United Kingdom

##### Average Amount Customer

In [0]:
# In each of the tables, we are analyzing the top six and bottom six nations.

display(Countries_detail.select("Country", "AVG_Amount_Customer").sort(Countries_detail.AVG_Amount_Customer.desc()).limit(6))

display(Countries_detail.select("Country", "AVG_Amount_Customer").sort(Countries_detail.AVG_Amount_Customer.asc()).limit(6))

Country AVG_Amount_Customer Netherlands 4392.24 Sweden 3834.3 Norway 3787.12 EIRE 2937.96 Japan 2568.36 Lithuania 1661.06

Databricks visualization. Run in Databricks to view.

Country AVG_Amount_Customer Poland 248.16 Austria 277.2 Channel Islands 363.53 Italy 405.75 Portugal 406.66 Belgium 452.48

Databricks visualization. Run in Databricks to view.

**Through the table we can tell that the countries with the highest AVG_Amount_Customer were:**

Netherlands, Sweden, Norway, EIRE, Japan and Lithuania

**On the other hand the countries with the lowest Amount of AVG_Amount_Customer were:**

Poland, Austia, Channel Islands, Italy Portugal and Belgium

We were just able to choose from the European Union countries, since the data available from PorData didn't give us the other countries.
So we based our analysis on the following countries:

**Germany**
This is 2nd  country that have the most sales, customers, orders and amount of products sold. So it was obvious to include on our analysis

**Netherlands**
This is the top country for both avg amount per order and AVG_Amount_Customer so with that we decided to include this country.

**Austria**
We decide to choose Austria as it is one of the countrys with worst indicators.

**Portugal**
Since we are from Portugal, we thought that would make sense to include it on our analysis.

In [0]:
# We selected the following nations after running several visualizations to assess the performance of the top and bottom performing nations.With that, we are using the where clause with the chosen nations to create a new dataframe.

Select_Countries = Countries_detail.select("*").where("Country IN ('Germany','Netherlands','Austria','Portugal')")

display(Select_Countries)

Country Total_Amount Total_Orders Amount_of_Products_Sold Total_Customers Year AVG_Amount_Order AVG_Amount_Customer Austria 277.2 1 51 1 2010 277.2 277.2 Germany 15241.14 30 6878 18 2010 508.04 846.73 Portugal 2439.97 6 984 6 2010 406.66 406.66 Netherlands 8784.48 3 6811 2 2010 2928.16 4392.24

## Importing the data from PorData

For our analysis, we are beginning to import the indicators that we think may be useful. After importing and individually transforming each CSV file for each indicator, we will merge them together based on the country name.

In [0]:
%fs ls /FileStore/tables

path name size modificationTime dbfs:/FileStore/tables/PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv 19199 1718054974000 dbfs:/FileStore/tables/PORDATA_Compensation_of_employees__Euro__xlsx.csv PORDATA_Compensation_of_employees__Euro__xlsx.csv 19589 1718054437000 dbfs:/FileStore/tables/PORDATA_Compensation_of_employees_per_capita__PPS_.csv PORDATA_Compensation_of_employees_per_capita__PPS_.csv 19981 1718054046000 dbfs:/FileStore/tables/PORDATA_GDP__Euro_.csv PORDATA_GDP__Euro_.csv 19989 1718055115000 dbfs:/FileStore/tables/PORDATA_Savings_rate_of_households.csv PORDATA_Savings_rate_of_households.csv 18483 1718051156000 dbfs:/FileStore/tables/csv_countrydata.xlsx csv_countrydata.xlsx 6207 1717975519000 dbfs:/FileStore/tables/csv_pordata.xlsx csv_pordata.xlsx 6207 1717975470000 dbfs:/FileStore/tables/insurance.csv insurance.csv 55628 1717703140000 dbfs:/FileStore/tables/movielens.txt movielens.txt 616155 1716487292000 dbfs:/FileStore/tables/onlineretail.csv onlineretail.csv 45580638 1717698189000 dbfs:/FileStore/tables/pages.txt pages.txt 64 1717696625000

In [0]:
# Like mentioned before we are importing the csv file from pordata

indicator_1 = spark.read.csv("dbfs:/FileStore/tables/PORDATA_Savings_rate_of_households.csv", header="true", sep=";", inferSchema="true")

In [0]:
# Overview of the dataset so we have an ideia to what needs to be done in order to have the columns the way we want
display(indicator_1)

_c0 _c1 _c2 _c3 _c4 _c5 _c6 _c7 _c8 _c9 _c10 _c11 _c12 _c13 _c14 _c15 _c16 _c17 _c18 _c19 _c20 _c21 _c22 _c23 _c24 _c25 _c26 _c27 _c28 _c29 _c30 _c31 _c32 _c33 _c34 _c35 _c36 _c37 _c38 _c39 _c40 _c41 _c42 _c43 _c44 _c45 _c46 _c47 _c48 _c49 _c50 _c51 _c52 _c53 _c54 _c55 _c56 _c57 _c58 _c59 _c60 _c61 _c62 _c63 _c64 _c65 _c66 _c67 _c68 _c69 _c70 _c71 _c72 _c73 _c74 _c75 _c76 _c77 _c78 _c79 _c80 _c81 _c82 _c83 _c84 _c85 _c86 _c87 _c88 _c89 _c90 _c91 _c92 _c93 _c94 _c95 _c96 _c97 _c98 _c99 _c100 _c101 _c102 _c103 _c104 _c105 _c106 _c107 _c108 _c109 _c110 _c111 _c112 _c113 _c114 _c115 _c116 _c117 _c118 _c119 _c120 _c121 _c122 _c123 _c124 _c125 _c126 _c127 _c128 _c129 _c130 _c131 _c132 _c133 _c134 _c135 _c136 _c137 _c138 _c139 _c140 _c141 _c142 _c143 _c144 _c145 _c146 _c147 _c148 _c149 _c150 _c151 _c152 _c153 _c154 _c155 _c156 _c157 _c158 _c159 _c160 _c161 _c162 _c163 _c164 _c165 _c166 _c167 _c168 _c169 _c170 _c171 _c172 _c173 _c174 _c175 _c176 _c177 _c178 _c179 _c180 _c181 _c182 _c183 _c184 _c185 _c186 _c187 _c188 _c189 _c190 _c191 _c192 _c193 _c194 _c195 _c196 _c197 _c198 _c199 _c200 _c201 _c202 _c203 _c204 _c205 _c206 _c207 _c208 _c209 _c210 _c211 _c212 _c213 _c214 _c215 _c216 _c217 _c218 _c219 _c220 _c221 _c222 _c223 _c224 _c225 _c226 _c227 _c228 _c229 _c230 _c231 _c232 _c233 _c234 _c235 _c236 _c237 _c238 _c239 _c240 _c241 _c242 _c243 _c244 _c245 _c246 _c247 _c248 _c249 _c250 _c251 _c252 _c253 _c254 _c255 null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null null

In [0]:
#We will use the first and third columns since we just need the country's column and the column containing the data about 2022.
indicator_1 = indicator_1.select('_c0','_c2')

In [0]:
# we are creating a DataFrame with the correct column name to help us understand.
indicator_1 = indicator_1.toDF("Country","savings_rate_households")

display(indicator_1)

Country savings_rate_households null null null null null null null null null null null null null null null null Groups/Countries null null null Years 2022 EU27 (2020) - European Union 27 (since 2020) x DE - Germany Pro 20,4 AT - Austria 15,5 BE - Belgium Pro 13,2 BG - Bulgaria x CY - Cyprus Pro 6,8 HR - Croatia Pro 6,5 DK - Denmark 14,0 SK - Slovakia 5,2 SI - Slovenia 13,9 ES - Spain 7,1 EE - Estonia 0,0 FI - Finland 8,1 FR - France Pro 17,4 GR - Greece Pro -2,6 HU - Hungary Pro 13,7 IE - Ireland x IT - Italy 10,0 LV - Latvia 3,4 LT - Lithuania 4,7 LU - Luxembourg 19,0 MT - Malta x NL - Netherlands Pro 20,6 PL - Poland 0,3 PT - Portugal Pro 6,2 CZ - Czech Republic 16,6 RO - Romania x SE - Sweden 17,3 UK - United Kingdom x null null null null null null null null Savings rate of households null Data Sources: Eurostat | NSI - Annual Sector Accounts null Source: PORDATA null Last updated: 2023-10-30 null null null null null null null Symbology null ? null ... null // null - null N null fr null null null null null null null null null Data obtained in https:www.pordata.pt in 10-06-2024 null null null

In [0]:
# It is evident that there are numerous null rows. That being said, we are only interested in the rows pertaining to the carefully selected countries. We will choose the necessary rows from our data using the where SQL function.

indicator_1= indicator_1.select('*').where("Country IN ('DE - Germany','NL - Netherlands','AT - Austria','PT - Portugal')")

In [0]:
display(indicator_1)

Country savings_rate_households DE - Germany Pro 20,4 AT - Austria 15,5 NL - Netherlands Pro 20,6 PT - Portugal Pro 6,2

After importing the first indicator we will do the same for our other indicators!

After importing the savings_rate_household we will import the GDP, the compensation_of_employees.

In [0]:
# After importing the csv file we copied the path: /FileStore/tables/indicator_2_compensation_of_employees.csv
# following the same logic that we performed before: 

indicator_2 = spark.read.csv("dbfs:/FileStore/tables/PORDATA_Compensation_of_employees__Euro__xlsx.csv", header="true", sep=";", inferSchema="true")
indicator_2 = indicator_2.select('_c0','_c2')
indicator_2 = indicator_2.toDF("Country","compensation_of_employees")
indicator_2= indicator_2.select('*').where("Country IN ('DE - Germany','NL - Netherlands','AT - Austria','PT - Portugal')")

In [0]:
display(indicator_2)

Country compensation_of_employees DE - Germany Pro 2 154 927,0 AT - Austria 236 939,7 NL - Netherlands s 483 301,0 PT - Portugal Pro 124 527,7

After importing the the compensation_of_employees we will import the GDP, the trade_balance_GDP.

In [0]:
indicator_3 = spark.read.csv("dbfs:/FileStore/tables/PORDATA_Balance_of_trade___as_a_percentage_of_GDP.csv", header="true", sep=";", inferSchema="true")
indicator_3 = indicator_3.select('_c0','_c2')
indicator_3 = indicator_3.toDF("Country","Trade_Balance_GDP")
indicator_3 = indicator_3.select('*').where("Country IN ('DE - Germany','NL - Netherlands','AT - Austria','PT - Portugal')")

In [0]:
display(indicator_3)

Country Trade_Balance_GDP DE - Germany Pro 5,6 AT - Austria 3,3 NL - Netherlands 10,1 PT - Portugal -1,9

After importing the GDPs above we will import the GDP POR_DATA_GDP_EURO.

In [0]:
indicator_4 = spark.read.csv("dbfs:/FileStore/tables/PORDATA_GDP__Euro_.csv", header="true", sep=";", inferSchema="true")
indicator_4 = indicator_4.select('_c0','_c2')
indicator_4 = indicator_4.toDF("Country","GDP")
indicator_4 = indicator_4.select('*').where("Country IN ('DE - Germany','NL - Netherlands','AT - Austria','PT - Portugal')")

In [0]:
display(indicator_4)

Country GDP DE - Germany Pro 4 121 160,0 AT - Austria 477 248,8 NL - Netherlands Pro 1 032 841,0 PT - Portugal Pro 265 741,9

Joining the indicators

In [0]:
#After importing and cleaning each of the indicators we needed to join them by the Country so that we can join with the dataset itself.
# So here we are performing some join in each iterations, addind one column at the time.

first_join = indicator_1.join(indicator_2, on ='Country')
second_join = first_join.join(indicator_3, on='Country')
joined_indicators = second_join.join(indicator_4, on='Country')
display(joined_indicators)

Country savings_rate_households compensation_of_employees Trade_Balance_GDP GDP DE - Germany Pro 20,4 Pro 2 154 927,0 Pro 5,6 Pro 4 121 160,0 AT - Austria 15,5 236 939,7 3,3 477 248,8 NL - Netherlands Pro 20,6 s 483 301,0 10,1 Pro 1 032 841,0 PT - Portugal Pro 6,2 Pro 124 527,7 -1,9 Pro 265 741,9

To join the indicators dataframe with the countries dataset we need to perform one last transformation on the indicators. In the Country Column we will need to keep only the country name.

In [0]:
# For that we will perform a split by the ' - ' to filter out the ISO codes and just keep the country name.
from pyspark.sql.functions import split

indicators = joined_indicators.withColumn('Country', split(joined_indicators['Country'], ' - ').getItem(1)) 
     
display(indicators)

Country savings_rate_households compensation_of_employees Trade_Balance_GDP GDP Germany Pro 20,4 Pro 2 154 927,0 Pro 5,6 Pro 4 121 160,0 Austria 15,5 236 939,7 3,3 477 248,8 Netherlands Pro 20,6 s 483 301,0 10,1 Pro 1 032 841,0 Portugal Pro 6,2 Pro 124 527,7 -1,9 Pro 265 741,9

We will merge the indicators dataframe with the real country data from the private exercise now that it is in the required format. so that the required analysis can be carried out.

In [0]:
Data_for_Analysis = Select_Countries.join(indicators, on ='Country')
display(Data_for_Analysis)

Country Total_Amount Total_Orders Amount_of_Products_Sold Total_Customers Year AVG_Amount_Order AVG_Amount_Customer savings_rate_households compensation_of_employees Trade_Balance_GDP GDP Austria 277.2 1 51 1 2010 277.2 277.2 15,5 236 939,7 3,3 477 248,8 Germany 15241.14 30 6878 18 2010 508.04 846.73 Pro 20,4 Pro 2 154 927,0 Pro 5,6 Pro 4 121 160,0 Portugal 2439.97 6 984 6 2010 406.66 406.66 Pro 6,2 Pro 124 527,7 -1,9 Pro 265 741,9 Netherlands 8784.48 3 6811 2 2010 2928.16 4392.24 Pro 20,6 s 483 301,0 10,1 Pro 1 032 841,0

### Final Analysis

Upon conducting extensive research on the PorData portal, we endeavored to identify indicators that hold significance for our project. Given that the dataset pertains to customer data from specific countries, we opted to focus on the following indicators: savings rate of households, balance of trade GDP, actual GDP per capita, and employees' compensation.

The analysis of the dataset reveals diverse economic behaviors and market characteristics across Austria, Germany, Portugal, and the Netherlands. In Austria, the data shows very low total amounts and orders, with only one customer. The savings rate of households is moderate at 15.5%, and the compensation of employees and GDP are relatively low. This suggests limited economic activity from the sampled data in Austria.

Germany, on the other hand, exhibits the highest total amount and number of orders among the countries listed. With 30 total orders and 18 customers, it indicates a larger and more active market. The savings rate of households is high at 20.4%, and the compensation of employees and GDP are the highest among the analyzed countries, contributing to a robust economic profile. The average amount per customer and order is moderate, indicating balanced spending behavior among German customers.

In Portugal, the total amount and number of orders are moderate, with six customers actively participating. However, Portugal's savings rate is the lowest among the countries at 6.2%, reflecting lower disposable income. The compensation of employees and GDP are also relatively low, pointing to economic constraints within the country.

The Netherlands shows a high total amount despite a low number of orders and customers, indicating high-value purchases. The savings rate of households is high at 20.6%, and both the compensation of employees and GDP are significant, suggesting a strong and affluent economy. The average amount per order and customer is notably high, underscoring the substantial purchasing power of Dutch customers.

In conclusion, Germany stands out with the highest economic activity and market size, while the Netherlands demonstrates high-value transactions despite having a smaller customer base. Portugal and Austria, however, reflect lower economic activity and spending. These insights can guide strategic decisions, such as market focus and resource allocation, for better targeting and engagement with customers in different regions.

In [0]:
display(Data_for_Analysis.select("Country","savings_rate_households"))

Country savings_rate_households Austria 15,5 Germany Pro 20,4 Portugal Pro 6,2 Netherlands Pro 20,6

When we look at the behavior of the saving rates per household in each country, the results align with our expectations. Portugal, as expected, has the lowest savings rate, considering that our country has the lowest salaries. Regarding Germany and the Netherlands, we already knew that these two countries had the highest average amount spent, so it was more than expected that the savings rates would be extremely high in comparison with the others. Austria falls in between, with a moderate savings rate of 15.5, reflecting its balanced economic position relative to the other countries.

#### <span style="color:purple"> **Good luck and I hope you enjoyed doing this assignment :) !!!** </span>

<span style="color:red"> **Don't forget to submit your exam in a folder containing both your outputs PDF and your notebook in the format of HTML. Once again, comment your code and don't forget to name the .zip file and notebook with your student numbers :) </span>